import React,{useCallback,useEffect,useState} from 'react';
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {del,get,patch,post} from '../api/client';
import {C} from '../theme';
import NativeIcon from '../components/NativeIcon';
import ScreenHeader from '../components/ScreenHeader';
import AccountProfileForm from './account/AccountProfileForm';
import {NotificationForm,PresenceForm,PrivacyForm} from './account/AccountPreferencesForms';
import {SafetyForm,SecurityForm} from './account/AccountSafetySecurity';
import {Action,Menu,commonStyles as cs} from './account/AccountSettingFields';

export type AccountSection='home'|'profile'|'privacy'|'presence'|'notifications'|'safety'|'security';
const ENDPOINT:Record<Exclude<AccountSection,'home'>,string>={profile:'/me/profile',privacy:'/me/privacy',presence:'/me/presence',notifications:'/me/notifications',safety:'/me/safety',security:'/me/security'};
export default function AccountSettingsScreen({initialSection='home',onBack,onMeChanged}:{initialSection?:AccountSection;onBack:()=>void;onMeChanged?:(me:any)=>void}){
 const [section,setSection]=useState<AccountSection>(initialSection);const [data,setData]=useState<any>(null);const [draft,setDraft]=useState<any>({});const [me,setMe]=useState<any>(null);const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 const refreshMe=useCallback(async()=>{try{const r=await get('/me');setMe(r.data);onMeChanged?.(r.data);return r.data}catch{return null}},[onMeChanged]);
 const load=useCallback(async(which:AccountSection)=>{setError('');if(which==='home'){await refreshMe();setData(null);setDraft({});return}setLoading(true);try{const r=await get(ENDPOINT[which as Exclude<AccountSection,'home'>]);setData(r.data||{});setDraft(r.data?.editable||{})}catch(e:any){setError(String(e?.message||e));setData(null);setDraft({})}finally{setLoading(false)}},[refreshMe]);
 useEffect(()=>{load(section)},[section,load]);
 const set=(key:string,value:any)=>setDraft((old:any)=>({...old,[key]:value}));
 const save=async()=>{if(!['profile','privacy','presence','notifications'].includes(section))return;setSaving(true);setError('');try{await patch(ENDPOINT[section as Exclude<AccountSection,'home'>],draft);await refreshMe();await load(section);Alert.alert('Saved','Your Private Gather settings were updated.')}catch(e:any){setError(String(e?.message||e))}finally{setSaving(false)}};
 const pause=async(days:number)=>{setSaving(true);try{await post('/me/pause',{days});await refreshMe();Alert.alert('Profile paused',`Your profile is paused for ${days} days.`)}catch(e:any){setError(String(e?.message||e))}finally{setSaving(false)}};
 const resume=async()=>{setSaving(true);try{await del('/me/pause');await refreshMe();Alert.alert('Profile visible','Your profile visibility has been resumed.')}catch(e:any){setError(String(e?.message||e))}finally{setSaving(false)}};
 const back=()=>section==='home'?onBack():setSection('home');
 return <ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><ScreenHeader title={title(section)} subtitle={section==='home'?'Native account, privacy and safety':'Private Gather 1.1.202 account API'} left={<Back onPress={back}/>}/>{error?<View style={s.error}><Text style={s.errorText}>{error}</Text>{error.toLowerCase().includes('not found')||error.includes('404')?<Text style={s.errorHint}>The website backend must be upgraded to Private Gather 1.1.202 before this native settings surface can save.</Text>:null}</View>:null}{loading?<View style={s.loading}><ActivityIndicator color={C.pink}/></View>:section==='home'?<Home me={me} open={setSection} pause={pause} resume={resume} saving={saving}/>:null}{!loading&&section==='profile'&&data?<AccountProfileForm data={data} draft={draft} set={set}/>:null}{!loading&&section==='privacy'&&data?<PrivacyForm data={data} draft={draft} set={set}/>:null}{!loading&&section==='presence'&&data?<PresenceForm data={data} draft={draft} set={set}/>:null}{!loading&&section==='notifications'&&data?<NotificationForm data={data} draft={draft} set={set}/>:null}{!loading&&section==='safety'&&data?<SafetyForm data={data} reload={()=>load('safety')} setError={setError}/>:null}{!loading&&section==='security'&&data?<SecurityForm data={data} reload={()=>load('security')} setError={setError}/>:null}{['profile','privacy','presence','notifications'].includes(section)&&data?<Pressable disabled={saving} onPress={save} style={[s.save,saving&&{opacity:.55}]}>{saving?<ActivityIndicator color="#fff"/>:<><NativeIcon ios="checkmark.circle.fill" android="check_circle" size={19} color="#fff"/><Text style={s.saveText}>Save changes</Text></>}</Pressable>:null}</ScrollView>
}
function Home({me,open,pause,resume,saving}:{me:any;open:(s:AccountSection)=>void;pause:(d:number)=>void;resume:()=>void;saving:boolean}){const paused=!!me?.profile_paused;return <View><View style={s.summary}><Text style={s.summaryTitle}>Account controls are native</Text><Text style={s.summaryCopy}>Profile, privacy, presence, notifications, safety and active-device controls use the same server rules as the Private Gather website.</Text></View><Text style={cs.section}>PROFILE</Text><Menu icon={['person.crop.circle.badge.checkmark','manage_accounts']} title="Edit profile" sub={`${Number(me?.profile_completion?.percent||0)}% complete · profile type stays permanent`} onPress={()=>open('profile')}/><Menu icon={['lock.shield.fill','shield_lock']} title="Privacy" sub="Visibility, location, online status and anonymous browsing" onPress={()=>open('privacy')}/><Menu icon={['location.circle.fill','travel_explore']} title="Presence & travel" sub="Availability, travel mode and read/typing privacy" onPress={()=>open('presence')}/><Menu icon={['bell.badge.fill','notifications_active']} title="Notifications" sub="Preview privacy, quiet settings and notification categories" onPress={()=>open('notifications')}/><Text style={cs.section}>SAFETY & SECURITY</Text><Menu icon={['hand.raised.fill','shield']} title="Blocked & hidden members" sub="Review your safety lists" onPress={()=>open('safety')}/><Menu icon={['lock.rotation','devices']} title="Sessions & devices" sub="Web sessions, native tokens and registered devices" onPress={()=>open('security')}/><View style={s.pauseCard}><Text style={s.pauseTitle}>{paused?'Profile paused':'Pause my profile'}</Text><Text style={s.pauseCopy}>{paused?`Paused until ${formatDate(me?.profile_paused_until)}`:'Temporarily remove your profile from discovery without deleting your account.'}</Text></View><View style={cs.buttonRow}>{paused?<Action label="Resume profile" onPress={resume} disabled={saving}/>:<><Action label="Pause 7 days" onPress={()=>pause(7)} disabled={saving}/><Action label="Pause 30 days" onPress={()=>pause(30)} disabled={saving}/></>}</View></View>}
function Back({onPress}:{onPress:()=>void}){return <Pressable onPress={onPress} style={s.back}><NativeIcon ios="chevron.left" android="arrow_back" size={21} color={C.text}/></Pressable>}
function title(section:AccountSection){return ({home:'Settings',profile:'Edit profile',privacy:'Privacy',presence:'Presence & travel',notifications:'Notifications',safety:'Safety',security:'Security & devices'} as const)[section]}
function formatDate(value:any){if(!value)return 'unknown';try{return new Date(value).toLocaleString()}catch{return String(value)}}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingHorizontal:16,paddingBottom:36},back:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,alignItems:'center',justifyContent:'center'},loading:{paddingVertical:50,alignItems:'center'},error:{borderWidth:1,borderColor:'rgba(255,66,89,.45)',backgroundColor:'rgba(255,66,89,.08)',borderRadius:16,padding:12,marginVertical:8},errorText:{color:'#ffafb9',fontSize:11,fontWeight:'800'},errorHint:{color:C.muted,fontSize:10,marginTop:5,lineHeight:15},summary:{borderWidth:1,borderColor:'rgba(41,217,255,.28)',backgroundColor:'rgba(41,217,255,.06)',borderRadius:20,padding:15,marginTop:8},summaryTitle:{color:C.text,fontSize:15,fontWeight:'900'},summaryCopy:{color:C.muted,fontSize:10.5,lineHeight:16,marginTop:6},pauseCard:{borderRadius:18,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,padding:14,marginTop:16},pauseTitle:{color:C.text,fontSize:14,fontWeight:'900'},pauseCopy:{color:C.muted,fontSize:10,lineHeight:15,marginTop:4},save:{height:52,borderRadius:17,backgroundColor:C.violet,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:18},saveText:{color:'#fff',fontWeight:'900',fontSize:13}});
