import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {get} from '../api/client';
import {Member} from '../app/types';
import {C} from '../theme';
import NativeIcon from '../components/NativeIcon';
import ProtectedImage from '../components/ProtectedImage';

type Row={id:number;member:Member;connectedAt?:string|null;mutual?:number|null};
export default function ConnectionsScreen({onBack,onMember,onMessage,onCall}:{onBack:()=>void;onMember:(id:number)=>void;onMessage:(m:Member)=>void;onCall:(m:Member,mode:'voice'|'video')=>void}){
 const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');const [q,setQ]=useState('');const [onlineOnly,setOnlineOnly]=useState(false);
 const load=useCallback(async()=>{try{setError('');const r=await get('/connections');const raw=Array.isArray(r.data)?r.data:[];setRows(raw.map(normalize).filter((x:Row)=>x.id>0))}catch(e:any){setError(String(e?.message||e))}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 const shown=useMemo(()=>rows.filter(x=>{const m=x.member;const text=`${m.display_name||''} ${m.username||''} ${m.location||''}`.toLowerCase();return(!q.trim()||text.includes(q.trim().toLowerCase()))&&(!onlineOnly||!!m.online)}),[rows,q,onlineOnly]);
 const online=rows.filter(x=>x.member.online).length;
 const refresh=async()=>{setRefreshing(true);await load();setRefreshing(false)};
 return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={C.pink}/>}>
   <View style={s.top}><Pressable onPress={onBack} style={s.back}><NativeIcon ios="chevron.left" android="arrow_back" size={22} color={C.cyan2}/><Text style={s.backText}>Back</Text></Pressable><Text style={s.title}>Connections</Text><View style={{width:62}}/></View>
   <View style={s.hero}><View><Text style={s.heroNumber}>{rows.length}</Text><Text style={s.heroLabel}>Accepted connections</Text></View><View style={s.heroDivider}/><View><Text style={[s.heroNumber,{color:C.green}]}>{online}</Text><Text style={s.heroLabel}>Online now</Text></View></View>
   <View style={s.search}><NativeIcon ios="magnifyingglass" android="search" size={19} color={C.faint}/><TextInput value={q} onChangeText={setQ} placeholder="Search connections" placeholderTextColor={C.faint} style={s.input}/><Pressable onPress={()=>setOnlineOnly(v=>!v)} style={[s.onlineButton,onlineOnly&&s.onlineButtonOn]}><View style={[s.onlineDot,!onlineOnly&&{backgroundColor:C.faint}]}/><Text style={[s.onlineText,onlineOnly&&{color:C.green}]}>Online</Text></Pressable></View>
   <View style={s.tabs}><View style={s.tabActive}><NativeIcon ios="person.2.fill" android="people" size={16} color={C.white}/><Text style={s.tabActiveText}>Accepted</Text></View><View style={s.tabDisabled}><Text style={s.tabDisabledText}>Requests</Text><Text style={s.soon}>SERVER NEXT</Text></View><View style={s.tabDisabled}><Text style={s.tabDisabledText}>Favorites</Text><Text style={s.soon}>SERVER NEXT</Text></View></View>
   {error?<Text style={s.error}>{error}</Text>:null}
   {loading?<ActivityIndicator color={C.pink} style={{marginTop:55}}/>:shown.map(x=><ConnectionCard key={x.id} row={x} onMember={onMember} onMessage={onMessage} onCall={onCall}/>) }
   {!loading&&!shown.length?<View style={s.empty}><NativeIcon ios="person.2.slash" android="person_off" size={40} color={C.faint}/><Text style={s.emptyTitle}>{rows.length?'No matching connections':'No connections yet'}</Text><Text style={s.emptyCopy}>{rows.length?'Try a different search or turn off Online only.':'When you connect with another member, they will appear here with quick message and call actions.'}</Text></View>:null}
 </ScrollView>
}
function ConnectionCard({row,onMember,onMessage,onCall}:{row:Row;onMember:(id:number)=>void;onMessage:(m:Member)=>void;onCall:(m:Member,mode:'voice'|'video')=>void}){const m=row.member;return <Pressable onPress={()=>onMember(m.id)} style={s.card}><View style={s.avatarWrap}><ProtectedImage uri={m.avatar_url} fallback={m.display_name||m.username||'PG'} style={s.avatar}/>{m.online?<View style={s.presence}/>:null}</View><View style={s.cardMain}><View style={s.nameLine}><Text numberOfLines={1} style={s.name}>{m.display_name||m.username||'Private Gather member'}</Text>{m.verified?<NativeIcon ios="checkmark.seal.fill" android="verified" size={16} color={C.green}/>:null}</View><Text style={s.handle}>@{m.username||''}</Text><Text numberOfLines={1} style={s.meta}>{m.online?(m.presence_label||'Online now'):(m.location||'Connected member')}</Text></View><View style={s.actions}>{m.can_message!==false?<Pressable accessibilityLabel="Message" onPress={e=>{e.stopPropagation?.();onMessage(m)}} style={s.action}><NativeIcon ios="message.fill" android="chat_bubble" size={19} color={C.cyan2}/></Pressable>:null}{m.can_call!==false?<Pressable accessibilityLabel="Call" onPress={e=>{e.stopPropagation?.();onCall(m,'voice')}} style={s.action}><NativeIcon ios="phone.fill" android="call" size={19} color={C.green}/></Pressable>:null}</View></Pressable>}
function normalize(row:any):Row{const source=row?.member||row?.connection||row?.user||row?.profile||row||{};const id=Number(source?.id||source?.member_id||row?.member_id||row?.user_id||0);const member:any={...source,id,display_name:String(source?.display_name||source?.name||row?.display_name||'Private Gather member'),username:String(source?.username||row?.username||''),avatar_url:source?.avatar_url||row?.avatar_url,verified:!!(source?.verified??row?.verified),online:!!(source?.online??row?.online),presence_label:source?.presence_label||row?.presence_label,location:source?.location||[source?.city,source?.state].filter(Boolean).join(', ')||row?.location,can_message:source?.can_message??true,can_call:source?.can_call??true};return{id,member,connectedAt:row?.connected_at||row?.accepted_at||null,mutual:Number(row?.mutual_count||0)||null}}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingHorizontal:16,paddingBottom:32},top:{height:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:62,flexDirection:'row',alignItems:'center',gap:3},backText:{color:C.cyan2,fontWeight:'800'},title:{color:C.text,fontSize:18,fontWeight:'900'},hero:{height:82,borderRadius:20,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,flexDirection:'row',alignItems:'center',justifyContent:'space-around',marginTop:4},heroNumber:{color:C.text,fontSize:23,fontWeight:'900',textAlign:'center'},heroLabel:{color:C.muted,fontSize:9,marginTop:3},heroDivider:{width:1,height:42,backgroundColor:C.line},search:{height:48,borderRadius:17,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,flexDirection:'row',alignItems:'center',gap:8,paddingLeft:13,marginTop:12},input:{flex:1,color:C.text,fontSize:13},onlineButton:{height:46,paddingHorizontal:11,borderLeftWidth:1,borderLeftColor:C.line,flexDirection:'row',alignItems:'center',gap:5},onlineButtonOn:{backgroundColor:'rgba(36,229,140,.06)'},onlineDot:{width:7,height:7,borderRadius:4,backgroundColor:C.green},onlineText:{color:C.muted,fontSize:9,fontWeight:'800'},tabs:{flexDirection:'row',gap:7,marginVertical:12},tabActive:{height:38,paddingHorizontal:11,borderRadius:13,backgroundColor:C.violet,flexDirection:'row',alignItems:'center',gap:6},tabActiveText:{color:C.white,fontSize:9.5,fontWeight:'900'},tabDisabled:{height:38,paddingHorizontal:10,borderRadius:13,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,justifyContent:'center'},tabDisabledText:{color:C.muted,fontSize:9,fontWeight:'800'},soon:{color:C.faint,fontSize:5.5,fontWeight:'900',letterSpacing:.5,marginTop:1},error:{color:'#ff8d8d',marginBottom:8},card:{minHeight:78,borderRadius:18,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,marginBottom:9,padding:11,flexDirection:'row',alignItems:'center',gap:11},avatarWrap:{position:'relative'},avatar:{width:54,height:54,borderRadius:18},presence:{position:'absolute',right:-2,bottom:-2,width:14,height:14,borderRadius:7,backgroundColor:C.green,borderWidth:3,borderColor:C.panel},cardMain:{flex:1,minWidth:0},nameLine:{flexDirection:'row',alignItems:'center',gap:5},name:{color:C.text,fontSize:13,fontWeight:'900',flexShrink:1},handle:{color:C.cyan2,fontSize:9.5,fontWeight:'700',marginTop:2},meta:{color:C.muted,fontSize:9,marginTop:5},actions:{flexDirection:'row',gap:6},action:{width:38,height:38,borderRadius:13,borderWidth:1,borderColor:C.line,backgroundColor:C.panel2,alignItems:'center',justifyContent:'center'},empty:{alignItems:'center',paddingTop:60,paddingHorizontal:30},emptyTitle:{color:C.text,fontSize:16,fontWeight:'900',marginTop:12},emptyCopy:{color:C.muted,fontSize:10.5,lineHeight:16,textAlign:'center',marginTop:5}});