import React,{useEffect,useRef,useState} from 'react';
import {FlatList,KeyboardAvoidingView,Platform,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView,useSafeAreaInsets} from 'react-native-safe-area-context';
import {get,post} from '../api/client';
import {ReverbClient} from '../realtime/ReverbClient';
import {C} from '../theme';
import ProtectedImage from '../components/ProtectedImage';
import NativeIcon from '../components/NativeIcon';
import SpeakerPicker from '../components/SpeakerPicker';

type Props={conversationId:number;rt:ReverbClient|null;userChannel?:string;onBack:()=>void;onCall:(peer:any,mode:'voice'|'video')=>void};
export default function ConversationScreen({conversationId,rt,userChannel,onBack,onCall}:Props){
 const insets=useSafeAreaInsets();
 const [data,setData]=useState<any>(null);const [draft,setDraft]=useState('');const [typing,setTyping]=useState('');const [error,setError]=useState('');const [speakerId,setSpeakerId]=useState<number|null>(null);const typingTimer=useRef<any>(null);const listRef=useRef<FlatList<any>>(null);const followTailRef=useRef(true);const tailTimers=useRef<any[]>([]);
 function clearTailTimers(){tailTimers.current.forEach(clearTimeout);tailTimers.current=[];}
 function forceTail(animated=true){
   followTailRef.current=true;clearTailTimers();
   const run=(a:boolean)=>{try{listRef.current?.scrollToEnd({animated:a})}catch{}};
   requestAnimationFrame(()=>run(animated));
   tailTimers.current.push(setTimeout(()=>run(animated),70));
   tailTimers.current.push(setTimeout(()=>run(false),190));
   tailTimers.current.push(setTimeout(()=>run(false),360));
 }
 async function load(){try{const d=await get(`/conversations/${conversationId}`);setData(d);const speakers=Array.isArray(d?.speakers)?d.speakers:[];setSpeakerId(prev=>speakers.some((x:any)=>Number(x.id)===Number(prev))?prev:(speakers[0]?Number(speakers[0].id):null));post(`/conversations/${conversationId}/read`,{}).catch(()=>{});forceTail(false);}catch(e:any){setError(String(e?.message||e))}}
 useEffect(()=>{followTailRef.current=true;load();return()=>clearTailTimers()},[conversationId]);
 useEffect(()=>{if(!rt||!conversationId)return;const unsubs:(()=>void)[]=[];unsubs.push(rt.subscribe(`presence-conversation.${conversationId}`,(e:any)=>{if(e.kind==='typing')setTyping(e.payload?.active===true?`${e.payload?.speaker_name||'Someone'} is typing…`:'');if(e.kind==='messages.read')setData((prev:any)=>prev?{...prev,receipt:e.payload}:prev);}));if(userChannel)unsubs.push(rt.subscribe(userChannel,(e:any)=>{const cid=Number(e.payload?.conversation_id||e.payload?.message?.conversation_id||0);if(cid!==conversationId)return;if(e.payload?.message){const incoming=e.payload.message;setData((prev:any)=>{if(!prev)return prev;const m=incoming,rows=[...(prev.messages||[])],i=rows.findIndex((x:any)=>Number(x.id)===Number(m.id));if(i>=0)rows[i]=m;else rows.push(m);return {...prev,messages:rows};});if(incoming.mine||followTailRef.current)forceTail(true);if(!incoming.mine)post(`/conversations/${conversationId}/read`,{}).catch(()=>{});}if(e.kind==='message.removed'){setData((prev:any)=>prev?{...prev,messages:(prev.messages||[]).filter((m:any)=>Number(m.id)!==Number(e.payload?.message_id||0))}:prev);}}));return()=>unsubs.forEach(fn=>fn())},[rt,userChannel,conversationId]);
 function changeDraft(value:string){setDraft(value);post(`/conversations/${conversationId}/typing`,{active:value.trim().length>0,speaker_profile_identity_id:speakerId||undefined}).catch(()=>{});clearTimeout(typingTimer.current);typingTimer.current=setTimeout(()=>post(`/conversations/${conversationId}/typing`,{active:false,speaker_profile_identity_id:speakerId||undefined}).catch(()=>{}),8000)}
 async function send(){const body=draft.trim();if(!body)return;setDraft('');followTailRef.current=true;clearTimeout(typingTimer.current);post(`/conversations/${conversationId}/typing`,{active:false,speaker_profile_identity_id:speakerId||undefined}).catch(()=>{});try{const r=await post(`/conversations/${conversationId}/messages`,{body,speaker_profile_identity_id:speakerId||undefined});if(r.message)setData((prev:any)=>{if(!prev)return prev;const rows=[...(prev.messages||[])];if(!rows.some((m:any)=>Number(m.id)===Number(r.message.id)))rows.push(r.message);return {...prev,messages:rows};});forceTail(true);}catch(e:any){setDraft(body);setError(String(e.message||e))}}
 const peer=data?.conversation;
 return <SafeAreaView style={s.page} edges={['top','left','right']}><View style={s.header}><Pressable style={s.iconBtn} onPress={onBack}><NativeIcon ios="chevron.left" android="arrow_back" size={24} color={C.cyan2}/></Pressable>{peer?<ProtectedImage uri={peer.avatar_url} fallback={peer.name} style={s.avatar}/>:null}<View style={s.headCopy}><View style={s.nameLine}><Text numberOfLines={1} style={s.name}>{peer?.name||'Conversation'}</Text>{peer?.presence?.online&&<View style={s.online}/>}</View><Text numberOfLines={1} style={s.presence}>{typing||peer?.presence?.label||'Private conversation'}</Text></View><View style={s.callRow}><Pressable accessibilityLabel="Voice call" disabled={!peer?.call_allowed} onPress={()=>peer&&onCall(peer,'voice')} style={[s.callBtn,!peer?.call_allowed&&s.disabled]}><NativeIcon ios="phone.fill" android="call" size={20} color={C.green}/></Pressable><Pressable accessibilityLabel="Video call" disabled={!peer?.call_allowed} onPress={()=>peer&&onCall(peer,'video')} style={[s.callBtn,!peer?.call_allowed&&s.disabled]}><NativeIcon ios="video.fill" android="videocam" size={21} color={C.green}/></Pressable></View></View>{error?<Text style={s.error}>{error}</Text>:null}<KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined} keyboardVerticalOffset={0}><FlatList ref={listRef} style={s.list} contentContainerStyle={s.listContent} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" data={data?.messages||[]} keyExtractor={(m:any)=>String(m.id)} renderItem={({item}:any)=><MessageBubble item={item}/>} scrollEventThrottle={16} onScroll={(e:any)=>{const n=e.nativeEvent;const distance=Number(n.contentSize?.height||0)-(Number(n.contentOffset?.y||0)+Number(n.layoutMeasurement?.height||0));followTailRef.current=distance<120;}} onContentSizeChange={()=>{if(followTailRef.current)requestAnimationFrame(()=>listRef.current?.scrollToEnd({animated:false}))}}/><View style={[s.composerWrap,{paddingBottom:Math.max(insets.bottom,8)}]}><SpeakerPicker speakers={data?.speakers||[]} value={speakerId} onChange={setSpeakerId} label="Speaking as"/><View style={s.composer}><Pressable style={s.add}><NativeIcon ios="plus" android="add" size={22} color={C.cyan2}/></Pressable><TextInput multiline maxLength={3000} value={draft} onChangeText={changeDraft} placeholder="Message" placeholderTextColor={C.faint} style={s.input}/><Pressable onPress={send} style={[s.send,!draft.trim()&&{opacity:.45}]} disabled={!draft.trim()}><NativeIcon ios="arrow.up" android="arrow_upward" size={21} color="#fff"/></Pressable></View></View></KeyboardAvoidingView></SafeAreaView>
}
function MessageBubble({item}:any){const call=item.type==='call_event'||item.call;const reactions=Array.isArray(item.reactions)?item.reactions:[];return <View style={[s.messageRow,item.mine&&{alignItems:'flex-end'}]}>{call?<View style={s.callEvent}><NativeIcon ios="phone.fill" android="call" size={14} color={C.cyan2}/><Text style={s.callEventText}>{item.body||item.call?.label||'Call'}</Text><Text style={s.callEventTime}>{item.created}</Text></View>:<><View style={[s.bubble,item.mine?s.mine:s.theirs]}>{item.reply&&<View style={s.reply}><Text style={s.replyAuthor}>{item.reply.author}</Text><Text numberOfLines={1} style={s.replyBody}>{item.reply.body}</Text></View>}<Text style={s.body}>{item.unsent?'Message removed':item.body}</Text>{item.attachments?.length>0&&<Text style={s.media}>Attachment · {item.attachments.length}</Text>}<View style={s.metaRow}><Text style={s.time}>{item.created}</Text>{item.mine&&<Text style={s.delivery}>{item.delivery_status==='read'?'✓✓':item.delivery_status==='delivered'?'✓✓':'✓'}</Text>}</View></View>{reactions.length>0&&<View style={s.reactions}>{reactions.map((r:any)=><View key={r.reaction} style={s.reaction}><Text style={s.reactionText}>{r.reaction} {r.count}</Text></View>)}</View>}</>}</View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},flex:{flex:1},header:{minHeight:66,flexDirection:'row',alignItems:'center',paddingHorizontal:9,borderBottomWidth:1,borderBottomColor:C.line,gap:8},iconBtn:{width:38,height:42,alignItems:'center',justifyContent:'center'},avatar:{width:42,height:42,borderRadius:14},headCopy:{flex:1},nameLine:{flexDirection:'row',alignItems:'center',gap:6},name:{color:C.text,fontWeight:'900',fontSize:14,maxWidth:'90%'},online:{width:8,height:8,borderRadius:4,backgroundColor:C.green},presence:{color:C.muted,fontSize:9,marginTop:2},callRow:{flexDirection:'row',gap:7},callBtn:{width:40,height:40,borderRadius:20,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,alignItems:'center',justifyContent:'center'},disabled:{opacity:.28},error:{color:'#ff8d8d',paddingHorizontal:14,paddingTop:5,fontSize:10},list:{flex:1},listContent:{paddingHorizontal:12,paddingTop:14,paddingBottom:18},messageRow:{marginBottom:7,alignItems:'flex-start'},bubble:{maxWidth:'82%',paddingHorizontal:13,paddingTop:10,paddingBottom:8,borderRadius:19},mine:{backgroundColor:'rgba(190,37,170,.72)',borderBottomRightRadius:5},theirs:{backgroundColor:C.panel2,borderBottomLeftRadius:5},body:{color:C.text,fontSize:14,lineHeight:19},time:{color:'#aba397',fontSize:8},delivery:{color:C.cyan2,fontSize:9,fontWeight:'900'},metaRow:{flexDirection:'row',justifyContent:'flex-end',alignItems:'center',gap:5,marginTop:5},reply:{borderLeftWidth:2,borderLeftColor:C.pink,paddingLeft:8,marginBottom:7},replyAuthor:{color:C.cyan2,fontSize:9,fontWeight:'900'},replyBody:{color:C.muted,fontSize:9,marginTop:2},media:{color:C.cyan2,fontSize:10,fontWeight:'700',marginTop:7},reactions:{flexDirection:'row',gap:4,marginTop:-4,paddingHorizontal:8},reaction:{paddingHorizontal:7,paddingVertical:3,borderRadius:10,backgroundColor:'#101c2c',borderWidth:1,borderColor:C.line},reactionText:{color:C.text,fontSize:9},callEvent:{alignSelf:'center',maxWidth:'90%',flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:12,paddingVertical:8,borderRadius:15,backgroundColor:'#0d1827',borderWidth:1,borderColor:C.line},callEventText:{color:C.muted,fontSize:10,fontWeight:'700'},callEventTime:{color:C.faint,fontSize:8},composerWrap:{paddingHorizontal:10,paddingTop:7,borderTopWidth:1,borderTopColor:C.line,backgroundColor:'#060c16'},composer:{minHeight:54,flexDirection:'row',alignItems:'flex-end',gap:8,paddingTop:2,paddingBottom:10},add:{width:40,height:40,borderRadius:20,backgroundColor:C.panel2,alignItems:'center',justifyContent:'center'},input:{flex:1,maxHeight:110,minHeight:40,borderRadius:20,backgroundColor:C.panel2,color:C.text,paddingHorizontal:15,paddingVertical:10,fontSize:14},send:{width:40,height:40,borderRadius:20,backgroundColor:C.pink,alignItems:'center',justifyContent:'center'}});
