import React,{useState} from 'react';
import {ActivityIndicator,KeyboardAvoidingView,Platform,Pressable,StatusBar,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {C,neonShadow} from '../theme';
import BrandLogo from '../components/BrandLogo';
export default function LoginScreen({onLogin}:{onLogin:(email:string,password:string)=>Promise<void>}){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const submit=async()=>{try{setError('');setBusy(true);await onLogin(email,password)}catch(e:any){setError(String(e.message||e))}finally{setBusy(false)}};
 return <SafeAreaView style={s.page}><StatusBar barStyle="light-content" backgroundColor={C.bg}/><View style={s.glowPink}/><View style={s.glowCyan}/><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={s.center}><BrandLogo/><Text style={s.eyebrow}>A MORE INTENTIONAL SOCIAL SPACE</Text><Text style={s.title}>More meaningful connections. <Text style={s.accent}>A more private you.</Text></Text><Text style={s.sub}>Real people, real experiences, and private conversations — all on your terms.</Text><View style={s.card}><TextInput autoCapitalize="none" autoCorrect={false} keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="Email" placeholderTextColor={C.faint} style={s.input}/><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor={C.faint} style={s.input}/>{error?<Text style={s.error}>{error}</Text>:null}<Pressable disabled={busy||!email||!password} onPress={submit} style={[s.button,(busy||!email||!password)&&{opacity:.5}]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>Sign in to Private Gather</Text>}</Pressable></View><View style={s.trust}><Text style={s.trustText}>♡  Connect</Text><Text style={s.trustText}>⌁  Explore</Text><Text style={s.trustText}>▣  Stay Private</Text></View><Text style={s.foot}>Private Gather · Native 1.1.200</Text></KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg,overflow:'hidden'},glowPink:{position:'absolute',width:260,height:260,borderRadius:130,backgroundColor:'rgba(255,53,211,.12)',left:-120,top:40},glowCyan:{position:'absolute',width:300,height:300,borderRadius:150,backgroundColor:'rgba(41,217,255,.10)',right:-150,bottom:20},center:{flex:1,justifyContent:'center',paddingHorizontal:24},eyebrow:{color:C.cyan2,fontSize:9,fontWeight:'900',letterSpacing:1.8,marginTop:28},title:{color:C.text,fontSize:31,lineHeight:37,fontWeight:'900',marginTop:9,maxWidth:350},accent:{color:C.pink},sub:{color:C.muted,fontSize:12,lineHeight:19,marginTop:11,maxWidth:340},card:{marginTop:26,padding:16,borderRadius:24,borderWidth:1,borderColor:'#2d4260',backgroundColor:'rgba(11,20,34,.95)',...neonShadow},input:{height:50,borderRadius:16,backgroundColor:C.panel2,borderWidth:1,borderColor:'#2b3d57',paddingHorizontal:14,color:C.text,marginBottom:10},error:{color:'#ff9aa8',fontSize:11,marginBottom:9},button:{height:52,borderRadius:16,backgroundColor:C.pink,borderWidth:1,borderColor:'#ff79e5',alignItems:'center',justifyContent:'center',marginTop:2},buttonText:{color:'#fff',fontWeight:'900'},trust:{flexDirection:'row',justifyContent:'space-between',gap:8,marginTop:22},trustText:{color:'#aebad0',fontSize:9,fontWeight:'800'},foot:{color:C.faint,fontSize:9,marginTop:18,textAlign:'center'}});
