import React,{useCallback,useEffect,useState} from 'react';
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View} from 'react-native';
import {get} from '../api/client';
import {Conversation} from '../app/types';
import {C} from '../theme';
import ScreenHeader from '../components/ScreenHeader';
import ProtectedImage from '../components/ProtectedImage';
import NativeIcon from '../components/NativeIcon';

export default function MessagesScreen({notificationCount,onNotifications,onConversation,pulse=0,onUnread}:{notificationCount:number;onNotifications:()=>void;onConversation:(id:number)=>void;pulse?:number;onUnread?:(n:number)=>void}){
  const [items,setItems]=useState<Conversation[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');
  const load=useCallback(async()=>{try{setError('');const r=await get('/conversations');const rows=r.conversations||[];setItems(rows);onUnread?.(rows.reduce((n:number,x:Conversation)=>n+Number(x.unread||0),0));}catch(e:any){setError(String(e?.message||e));}finally{setLoading(false)}},[onUnread]);
  useEffect(()=>{load()},[load,pulse]);const refresh=async()=>{setRefreshing(true);await load();setRefreshing(false)};
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={C.pink}/>}><ScreenHeader title="Messages" subtitle="Private, realtime conversations" onNotifications={onNotifications} notificationCount={notificationCount}/>{error?<Text style={s.error}>{error}</Text>:null}{loading?<ActivityIndicator color={C.pink} style={{marginTop:60}}/>:items.map(item=><Pressable key={item.id} onPress={()=>onConversation(item.id)} style={s.row}><View style={s.avatarWrap}><ProtectedImage uri={item.avatar_url} fallback={item.name} style={s.avatar}/>{item.presence?.online&&<View style={s.online}/>}</View><View style={s.copy}><View style={s.nameRow}><Text numberOfLines={1} style={s.name}>{item.name}</Text>{item.verified&&<Text style={s.verified}>✓</Text>}</View><Text numberOfLines={1} style={[s.preview,item.unread>0&&s.previewUnread]}>{item.preview}</Text><Text style={s.presence}>{item.presence?.label||item.updated_at||''}</Text></View>{item.unread>0&&<View style={s.badge}><Text style={s.badgeText}>{item.unread>99?'99+':item.unread}</Text></View>}</Pressable>)}{!loading&&!items.length&&<View style={s.empty}><NativeIcon ios="message.fill" android="chat_bubble" size={34} color={C.cyan2}/><Text style={s.emptyTitle}>No conversations yet</Text><Text style={s.emptySub}>Discover members and start a private conversation.</Text></View>}</ScrollView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingHorizontal:16,paddingBottom:28},error:{color:'#ff8d8d',marginBottom:8},row:{minHeight:78,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:'#1e252e',paddingVertical:11},avatarWrap:{position:'relative'},avatar:{width:56,height:56,borderRadius:19},online:{position:'absolute',right:0,bottom:1,width:13,height:13,borderRadius:7,backgroundColor:C.green,borderWidth:2,borderColor:C.bg},copy:{flex:1},nameRow:{flexDirection:'row',alignItems:'center',gap:6},name:{color:C.text,fontSize:15,fontWeight:'900',maxWidth:'88%'},verified:{color:C.green,fontWeight:'900'},preview:{color:C.muted,fontSize:11,marginTop:4},previewUnread:{color:'#ddd7ce',fontWeight:'700'},presence:{color:C.faint,fontSize:9,marginTop:4},badge:{minWidth:25,height:25,borderRadius:13,paddingHorizontal:5,backgroundColor:C.pink,alignItems:'center',justifyContent:'center'},badgeText:{color:'#fff',fontWeight:'900',fontSize:10},empty:{alignItems:'center',paddingTop:80},emptyIcon:{color:C.gold,fontSize:34},emptyTitle:{color:C.text,fontWeight:'900',fontSize:17,marginTop:10},emptySub:{color:C.muted,fontSize:11,textAlign:'center',marginTop:5,maxWidth:260}});
