import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {get,post} from '../api/client';
import {NotificationCard} from '../app/types';
import {C} from '../theme';
import ProtectedImage from '../components/ProtectedImage';
import NativeIcon from '../components/NativeIcon';

type FilterKey='all'|'messages'|'social'|'calls'|'events'|'clubs'|'verification'|'system';
const filters:{key:FilterKey;label:string;ios:string;android:string}[]=[
 {key:'all',label:'All',ios:'tray.full.fill',android:'inbox'},
 {key:'messages',label:'Messages',ios:'message.fill',android:'chat_bubble'},
 {key:'social',label:'Connections',ios:'person.2.fill',android:'people'},
 {key:'calls',label:'Calls',ios:'phone.fill',android:'call'},
 {key:'events',label:'Events',ios:'calendar',android:'event'},
 {key:'clubs',label:'Clubs',ios:'building.2.fill',android:'groups'},
 {key:'verification',label:'Verification',ios:'checkmark.shield.fill',android:'verified_user'},
 {key:'system',label:'System',ios:'gearshape.fill',android:'settings'},
];

export default function NotificationsScreen({onBack,onTarget,onCount}:{onBack:()=>void;onTarget:(t:NonNullable<NotificationCard['target']>)=>void;onCount:(n:number)=>void}){
 const [items,setItems]=useState<NotificationCard[]>([]);const [unread,setUnread]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [filter,setFilter]=useState<FilterKey>('all');
 const load=useCallback(async()=>{try{setLoading(true);setError('');const r=await get('/notifications');setItems(Array.isArray(r.data)?r.data:[]);setUnread(Number(r.unread_count||0));onCount(Number(r.unread_count||0));}catch(e:any){setError(String(e?.message||e));}finally{setLoading(false)}},[onCount]);useEffect(()=>{load()},[load]);
 const markAll=async()=>{try{await post('/notifications/read-all',{});setUnread(0);setItems(v=>v.map(n=>({...n,read:true})));onCount(0)}catch(e:any){setError(String(e?.message||e))}};
 const shown=useMemo(()=>filter==='all'?items:items.filter(n=>bucket(n)===filter),[items,filter]);
 const counts=useMemo(()=>{const map:any={all:items.length};for(const f of filters.slice(1))map[f.key]=items.filter(n=>bucket(n)===f.key).length;return map},[items]);
 return <ScrollView style={s.page} contentContainerStyle={s.content} stickyHeaderIndices={[2]}>
   <View style={s.top}><Pressable onPress={onBack} style={s.backButton}><NativeIcon ios="chevron.left" android="arrow_back" size={22} color={C.cyan2}/><Text style={s.back}>Back</Text></Pressable><Text style={s.title}>Notifications</Text><Pressable disabled={!unread} onPress={markAll}><Text style={[s.read,!unread&&{opacity:.35}]}>Mark read</Text></Pressable></View>
   <View style={s.summary}><View><Text style={s.lead}>{unread?`${unread} unread update${unread===1?'':'s'}`:'You’re all caught up.'}</Text><Text style={s.sub}>Messages, connections, calls, events, clubs and account notices</Text></View><Pressable onPress={()=>load()} style={s.refresh}><NativeIcon ios="arrow.clockwise" android="refresh" size={19} color={C.cyan2}/></Pressable></View>
   <View style={s.filterShell}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{filters.map(f=><Pressable key={f.key} onPress={()=>setFilter(f.key)} style={[s.chip,filter===f.key&&s.chipOn]}><NativeIcon ios={f.ios} android={f.android} size={15} color={filter===f.key?C.white:C.cyan2}/><Text style={[s.chipText,filter===f.key&&s.chipTextOn]}>{f.label}</Text>{counts[f.key]>0?<View style={[s.count,filter===f.key&&s.countOn]}><Text style={s.countText}>{counts[f.key]>99?'99+':counts[f.key]}</Text></View>:null}</Pressable>)}</ScrollView></View>
   {error?<Text style={s.error}>{error}</Text>:null}
   {loading?<ActivityIndicator color={C.pink} style={{marginTop:50}}/>:shown.map(n=><Pressable disabled={!n.target} onPress={()=>n.target&&onTarget(n.target)} key={n.id} style={[s.row,!n.read&&s.unread]}>{n.avatar?<ProtectedImage uri={n.avatar} fallback={n.actor_name||n.title} style={s.avatar}/>:<View style={s.icon}><Text style={s.iconText}>{n.icon||'PG'}</Text></View>}<View style={{flex:1}}><View style={s.line}><Text numberOfLines={1} style={s.name}>{n.title}</Text><Text style={s.time}>{n.time}</Text></View><View style={s.categoryRow}><Text style={s.cat}>{n.category_label}</Text>{!n.read?<Text style={s.newLabel}>NEW</Text>:null}</View>{n.message?<Text numberOfLines={3} style={s.message}>{n.message}</Text>:null}</View>{n.target?<NativeIcon ios="chevron.right" android="chevron_right" size={18} color={C.faint}/>:null}</Pressable>)}
   {!loading&&shown.length===0?<View style={s.empty}><NativeIcon ios="checkmark.circle.fill" android="check_circle" size={38} color={C.green}/><Text style={s.emptyTitle}>Nothing here</Text><Text style={s.emptyCopy}>There are no {filter==='all'?'notifications':filters.find(f=>f.key===filter)?.label.toLowerCase()} in your recent activity.</Text></View>:null}
 </ScrollView>
}
function bucket(n:NotificationCard):FilterKey{const raw=`${n.category||''} ${n.category_label||''} ${n.type||''}`.toLowerCase();if(/message|chat|reply/.test(raw))return'messages';if(/call|voice|video|missed/.test(raw))return'calls';if(/event|rsvp|gathering|party/.test(raw))return'events';if(/club|venue|host/.test(raw))return'clubs';if(/verif|identity|age/.test(raw))return'verification';if(/connection|friend|reaction|comment|album|profile|view/.test(raw))return'social';return'system'}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{padding:16,paddingBottom:30},top:{height:56,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},backButton:{flexDirection:'row',alignItems:'center',gap:3,minWidth:70},back:{color:C.cyan2,fontWeight:'800'},title:{color:C.text,fontWeight:'900',fontSize:18},read:{color:C.cyan2,fontWeight:'800',fontSize:11},summary:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,marginBottom:10},lead:{color:C.text,fontSize:13,fontWeight:'800'},sub:{color:C.muted,fontSize:9.5,marginTop:3,maxWidth:300},refresh:{width:38,height:38,borderRadius:13,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,alignItems:'center',justifyContent:'center'},filterShell:{backgroundColor:C.bg,paddingVertical:7,marginHorizontal:-16,paddingHorizontal:16,marginBottom:8},filters:{gap:7,paddingRight:10},chip:{height:36,paddingHorizontal:10,borderRadius:13,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,flexDirection:'row',alignItems:'center',gap:6},chipOn:{backgroundColor:C.violet,borderColor:C.violet},chipText:{color:C.text,fontSize:9.5,fontWeight:'800'},chipTextOn:{color:C.white},count:{minWidth:18,height:18,paddingHorizontal:4,borderRadius:9,backgroundColor:C.panel3,alignItems:'center',justifyContent:'center'},countOn:{backgroundColor:'rgba(255,255,255,.18)'},countText:{color:C.white,fontSize:8,fontWeight:'900'},error:{color:'#ff8d8d',marginBottom:8},row:{flexDirection:'row',gap:11,padding:13,borderRadius:17,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,marginBottom:8,alignItems:'center'},unread:{backgroundColor:'rgba(155,92,255,.09)',borderColor:'rgba(155,92,255,.45)'},avatar:{width:46,height:46,borderRadius:15},icon:{width:46,height:46,borderRadius:15,backgroundColor:C.panel3,alignItems:'center',justifyContent:'center'},iconText:{color:C.cyan2,fontWeight:'900'},line:{flexDirection:'row',justifyContent:'space-between',gap:8},name:{flex:1,color:C.text,fontWeight:'900',fontSize:13},time:{color:C.faint,fontSize:9},categoryRow:{flexDirection:'row',alignItems:'center',gap:6,marginTop:2},cat:{color:C.violet,fontSize:9,fontWeight:'800'},newLabel:{color:C.pink,fontSize:7.5,fontWeight:'900',letterSpacing:.7},message:{color:C.muted,fontSize:11,lineHeight:15,marginTop:4},empty:{alignItems:'center',paddingTop:58,paddingHorizontal:28},emptyTitle:{color:C.text,fontSize:16,fontWeight:'900',marginTop:10},emptyCopy:{color:C.muted,fontSize:10.5,lineHeight:16,textAlign:'center',marginTop:5}});