import React,{useCallback,useEffect,useState} from 'react';
import {Linking,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {get} from '../api/client';
import {clearToken} from '../auth/session';
import {C} from '../theme';
import ScreenHeader from '../components/ScreenHeader';
import ProtectedImage from '../components/ProtectedImage';
import NativeIcon from '../components/NativeIcon';

export default function ProfileScreen({me,notificationCount,onNotifications,onClubs,onLogout,onMember}:{me:any;notificationCount:number;onNotifications:()=>void;onClubs:()=>void;onLogout:()=>void;onMember:(id:number)=>void}){
 const [connections,setConnections]=useState<any[]>([]);const load=useCallback(()=>{get('/connections').then(r=>setConnections(r.data||[])).catch(()=>{})},[]);useEffect(()=>{load()},[load]);
 const logout=async()=>{try{const {api}=await import('../api/client');await api('/token',{method:'DELETE'});}catch{}await clearToken();onLogout()};
 return <ScrollView style={s.page} contentContainerStyle={s.content}><ScreenHeader title="Me" subtitle="Your profile and privacy" onNotifications={onNotifications} notificationCount={notificationCount}/><View style={s.profileCard}><View style={s.cover}><ProtectedImage uri={me?.cover_url} fallback={me?.display_name||'PG'} style={StyleSheet.absoluteFillObject as any}/><View style={s.coverGlow}/></View><ProtectedImage uri={me?.avatar_url} fallback={me?.display_name||'PG'} style={s.avatar}/><View style={s.profileCopy}><View style={s.nameRow}><Text style={s.name}>{me?.display_name||'Private Gather'}</Text>{me?.verified&&<NativeIcon ios="checkmark.seal.fill" android="verified" size={19} color={C.green}/>}</View><Text style={s.handle}>@{me?.username||''}</Text><Text style={s.meta}>{[me?.profile_type,me?.city,me?.state].filter(Boolean).join(' · ')}</Text></View></View><View style={s.stats}><View style={s.stat}><Text style={s.statValue}>{connections.length}</Text><Text style={s.statLabel}>Connections</Text></View><View style={s.stat}><Text style={s.statValue}>{notificationCount}</Text><Text style={s.statLabel}>Unread</Text></View><View style={s.stat}><Text style={s.statValue}>{me?.verified?'Yes':'No'}</Text><Text style={s.statLabel}>Verified</Text></View></View><Text style={s.section}>ACCOUNT</Text><Menu ios="person.crop.circle" android="account_circle" title="View my profile" sub="See your member profile" onPress={()=>me?.id&&onMember(Number(me.id))}/><Menu ios="building.2.fill" android="groups" title="Clubs" sub="Verified communities and venues" onPress={onClubs}/><Menu ios="bell.fill" android="notifications" title="Notifications" sub="Messages, reactions and events" onPress={onNotifications}/><Text style={s.section}>PRIVACY</Text><Menu ios="lock.shield.fill" android="shield_lock" title="Privacy & Safety" sub="Visibility, blocking and discreet controls" onPress={()=>Linking.openURL('https://member.privategather.com/settings/privacy')}/><Menu ios="gearshape.fill" android="settings" title="Settings" sub="Calling, notifications and preferences" onPress={()=>Linking.openURL('https://member.privategather.com/settings')}/><Pressable onPress={logout} style={s.logout}><NativeIcon ios="rectangle.portrait.and.arrow.right" android="logout" size={18} color="#ff8ea0"/><Text style={s.logoutText}>Sign out</Text></Pressable></ScrollView>
}
function Menu({ios,android,title,sub,onPress}:{ios:string;android:string;title:string;sub:string;onPress?:()=>void}){return <Pressable onPress={onPress} style={s.menu}><View style={s.menuIcon}><NativeIcon ios={ios} android={android} size={20} color={C.cyan2}/></View><View style={{flex:1}}><Text style={s.menuTitle}>{title}</Text><Text style={s.menuSub}>{sub}</Text></View><NativeIcon ios="chevron.right" android="chevron_right" size={20} color={C.faint}/></Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingHorizontal:16,paddingBottom:30},profileCard:{borderRadius:24,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,overflow:'hidden',marginTop:8},cover:{height:82,backgroundColor:'#08172b',overflow:'hidden'},coverGlow:{position:'absolute',right:-30,top:-70,width:180,height:180,borderRadius:90,backgroundColor:'rgba(255,53,211,.16)'},avatar:{width:84,height:84,borderRadius:26,borderWidth:3,borderColor:C.panel,marginTop:-38,marginLeft:16},profileCopy:{paddingHorizontal:16,paddingBottom:16},nameRow:{flexDirection:'row',alignItems:'center',gap:7,marginTop:8},name:{color:C.text,fontSize:21,fontWeight:'900'},handle:{color:C.cyan2,fontSize:11,fontWeight:'700',marginTop:2},meta:{color:C.muted,fontSize:11,marginTop:6,textTransform:'capitalize'},stats:{height:72,flexDirection:'row',borderWidth:1,borderColor:C.line,borderRadius:20,backgroundColor:C.panel,marginTop:12},stat:{flex:1,alignItems:'center',justifyContent:'center'},statValue:{color:C.text,fontSize:18,fontWeight:'900'},statLabel:{color:C.muted,fontSize:9,marginTop:3},section:{color:C.faint,fontSize:9,fontWeight:'900',letterSpacing:1.8,marginTop:22,marginBottom:5},menu:{minHeight:65,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderBottomColor:'#202b3a'},menuIcon:{width:40,height:40,borderRadius:14,backgroundColor:C.panel2,alignItems:'center',justifyContent:'center'},menuTitle:{color:C.text,fontWeight:'800',fontSize:13},menuSub:{color:C.muted,fontSize:10,marginTop:3},logout:{height:50,borderRadius:16,borderWidth:1,borderColor:'rgba(255,66,89,.38)',backgroundColor:'rgba(255,66,89,.08)',alignItems:'center',justifyContent:'center',marginTop:24,flexDirection:'row',gap:8},logoutText:{color:'#ff8ea0',fontWeight:'900'}});
