import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {Linking,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {get} from '../api/client';
import {clearToken} from '../auth/session';
import {Member} from '../app/types';
import {C} from '../theme';
import ScreenHeader from '../components/ScreenHeader';
import ProtectedImage from '../components/ProtectedImage';
import NativeIcon from '../components/NativeIcon';
import ConnectionsScreen from './ConnectionsScreen';
import SafetyCenterScreen from './SafetyCenterScreen';
import {openMessenger} from '../messenger/MessengerBridge';

export default function ProfileScreen({me,notificationCount,onNotifications,onClubs,onLogout,onMember}:{me:any;notificationCount:number;onNotifications:()=>void;onClubs:()=>void;onLogout:()=>void;onMember:(id:number)=>void}){
 const [connections,setConnections]=useState<any[]>([]);const [detail,setDetail]=useState<Member|null>(null);const [connectionsOpen,setConnectionsOpen]=useState(false);const [safetyOpen,setSafetyOpen]=useState(false);
 const load=useCallback(()=>{get('/connections').then(r=>setConnections(r.data||[])).catch(()=>{});if(me?.id)get(`/members/${Number(me.id)}`).then(r=>setDetail(r.data||null)).catch(()=>{})},[me?.id]);useEffect(()=>{load()},[load]);
 const completion=useMemo(()=>profileCompletion(me,detail),[me,detail]);
 const verificationDone=(me?.identity_verified?1:0)+(me?.age_verified?1:0);const verificationPct=Math.round((verificationDone/2)*100);
 const logout=async()=>{try{const {api}=await import('../api/client');await api('/token',{method:'DELETE'});}catch{}await clearToken();onLogout()};
 const message=(m:Member)=>openMessenger({userId:Number(m.id)}).catch(()=>{});const call=(m:Member,mode:'voice'|'video')=>openMessenger({userId:Number(m.id),callMode:mode}).catch(()=>{});
 if(connectionsOpen)return <ConnectionsScreen onBack={()=>{setConnectionsOpen(false);load()}} onMember={onMember} onMessage={message} onCall={call}/>;
 if(safetyOpen)return <SafetyCenterScreen onBack={()=>setSafetyOpen(false)}/>;
 return <ScrollView style={s.page} contentContainerStyle={s.content}><ScreenHeader title="Me" subtitle="Your profile and privacy" onNotifications={onNotifications} notificationCount={notificationCount}/><View style={s.profileCard}><View style={s.cover}><ProtectedImage uri={me?.cover_url} fallback={me?.display_name||'PG'} style={StyleSheet.absoluteFill as any}/><View style={s.coverGlow}/></View><ProtectedImage uri={me?.avatar_url} fallback={me?.display_name||'PG'} style={s.avatar}/><View style={s.profileCopy}><View style={s.nameRow}><Text style={s.name}>{me?.display_name||'Private Gather'}</Text>{me?.verified&&<NativeIcon ios="checkmark.seal.fill" android="verified" size={19} color={C.green}/>}</View><Text style={s.handle}>@{me?.username||''}</Text><Text style={s.meta}>{[me?.profile_type,me?.city,me?.state].filter(Boolean).join(' · ')}</Text></View></View><Pressable onPress={()=>setConnectionsOpen(true)} style={s.stats}><View style={s.stat}><Text style={s.statValue}>{connections.length}</Text><Text style={s.statLabel}>Connections</Text></View><View style={s.stat}><Text style={s.statValue}>{notificationCount}</Text><Text style={s.statLabel}>Unread</Text></View><View style={s.stat}><Text style={s.statValue}>{me?.verified?'Yes':'No'}</Text><Text style={s.statLabel}>Verified</Text></View></Pressable>

 <View style={s.progressCard}>
   <View style={s.progressHead}><View style={s.progressIcon}><NativeIcon ios="person.crop.circle.badge.checkmark" android="manage_accounts" size={21} color={C.violet}/></View><View style={{flex:1}}><Text style={s.progressTitle}>Profile completion</Text><Text style={s.progressCopy}>{completion.percent}% complete · {completion.done} of {completion.total} profile essentials</Text></View><Text style={s.progressNumber}>{completion.percent}%</Text></View>
   <View style={s.track}><View style={[s.fill,{width:`${completion.percent}%` as any}]}/></View>
   {completion.next?<Text style={s.next}>Next: {completion.next}</Text>:<Text style={s.complete}>Your core profile is complete.</Text>}
 </View>

 <View style={s.progressCard}>
   <View style={s.progressHead}><View style={s.progressIcon}><NativeIcon ios="checkmark.shield.fill" android="verified_user" size={21} color={verificationDone===2?C.green:C.cyan2}/></View><View style={{flex:1}}><Text style={s.progressTitle}>Verification</Text><Text style={s.progressCopy}>{verificationDone===2?'Identity and age verification complete':`${verificationDone} of 2 verification checks complete`}</Text></View><Text style={[s.progressNumber,verificationDone===2&&{color:C.green}]}>{verificationPct}%</Text></View>
   <View style={s.track}><View style={[s.verifyFill,{width:`${verificationPct}%` as any}]}/></View>
   <View style={s.checkRow}><Check done={!!me?.identity_verified} label="Identity"/><Check done={!!me?.age_verified} label="Age 18+"/></View>
 </View>

 <Text style={s.section}>ACCOUNT</Text><Menu ios="person.crop.circle" android="account_circle" title="View my profile" sub="Preview the profile other members see" onPress={()=>me?.id&&onMember(Number(me.id))}/><Menu ios="person.2.fill" android="people" title="Connections" sub={`${connections.length} accepted · quick message and call actions`} onPress={()=>setConnectionsOpen(true)}/><Menu ios="building.2.fill" android="groups" title="Clubs" sub="Verified communities and venues" onPress={onClubs}/><Menu ios="bell.fill" android="notifications" title="Notifications" sub="Messages, reactions and events" onPress={onNotifications}/><Text style={s.section}>PRIVACY</Text><Menu ios="lock.shield.fill" android="shield_lock" title="Safety Center" sub="App Lock, biometrics, PIN and discreet safety controls" onPress={()=>setSafetyOpen(true)}/><Menu ios="gearshape.fill" android="settings" title="Settings" sub="Calling, notifications and preferences" onPress={()=>Linking.openURL('https://member.privategather.com/settings')}/><Pressable onPress={logout} style={s.logout}><NativeIcon ios="rectangle.portrait.and.arrow.right" android="logout" size={18} color="#ff8ea0"/><Text style={s.logoutText}>Sign out</Text></Pressable></ScrollView>
}
function profileCompletion(me:any,m:Member|null){const rows:[boolean,string][]=[
 [!!me?.avatar_url,'Add a profile photo'],[!!me?.cover_url,'Add a cover photo'],[!!String(m?.headline||'').trim(),'Add a profile headline'],[!!String(m?.about||'').trim(),'Write your About section'],[!!String(m?.looking_for||'').trim(),'Describe what you are looking for'],[!!m?.interests?.length,'Choose your interests'],[!!String(m?.location||[me?.city,me?.state].filter(Boolean).join(' ')).trim(),'Add your location'],[!!String(m?.relationship_status||'').trim(),'Add relationship details'],[!!String(m?.boundaries||'').trim(),'Add boundaries and expectations'],[!!(me?.identity_verified&&me?.age_verified),'Complete verification']];const done=rows.filter(x=>x[0]).length;return{done,total:rows.length,percent:Math.round(done/rows.length*100),next:rows.find(x=>!x[0])?.[1]||''}}
function Check({done,label}:{done:boolean;label:string}){return <View style={s.check}><NativeIcon ios={done?'checkmark.circle.fill':'circle'} android={done?'check_circle':'radio_button_unchecked'} size={17} color={done?C.green:C.faint}/><Text style={[s.checkText,done&&{color:C.text}]}>{label}</Text></View>}
function Menu({ios,android,title,sub,onPress}:{ios:string;android:string;title:string;sub:string;onPress?:()=>void}){return <Pressable onPress={onPress} style={s.menu}><View style={s.menuIcon}><NativeIcon ios={ios} android={android} size={20} color={C.cyan2}/></View><View style={{flex:1}}><Text style={s.menuTitle}>{title}</Text><Text style={s.menuSub}>{sub}</Text></View><NativeIcon ios="chevron.right" android="chevron_right" size={20} color={C.faint}/></Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingHorizontal:16,paddingBottom:30},profileCard:{borderRadius:24,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,overflow:'hidden',marginTop:8},cover:{height:82,backgroundColor:'#08172b',overflow:'hidden'},coverGlow:{position:'absolute',right:-30,top:-70,width:180,height:180,borderRadius:90,backgroundColor:'rgba(255,53,211,.16)'},avatar:{width:84,height:84,borderRadius:26,borderWidth:3,borderColor:C.panel,marginTop:-38,marginLeft:16},profileCopy:{paddingHorizontal:16,paddingBottom:16},nameRow:{flexDirection:'row',alignItems:'center',gap:7,marginTop:8},name:{color:C.text,fontSize:21,fontWeight:'900'},handle:{color:C.cyan2,fontSize:11,fontWeight:'700',marginTop:2},meta:{color:C.muted,fontSize:11,marginTop:6,textTransform:'capitalize'},stats:{height:72,flexDirection:'row',borderWidth:1,borderColor:C.line,borderRadius:20,backgroundColor:C.panel,marginTop:12},stat:{flex:1,alignItems:'center',justifyContent:'center'},statValue:{color:C.text,fontSize:18,fontWeight:'900'},statLabel:{color:C.muted,fontSize:9,marginTop:3},progressCard:{borderWidth:1,borderColor:C.line,borderRadius:20,backgroundColor:C.panel,marginTop:12,padding:14},progressHead:{flexDirection:'row',alignItems:'center',gap:10},progressIcon:{width:40,height:40,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:C.panel2},progressTitle:{color:C.text,fontSize:13,fontWeight:'900'},progressCopy:{color:C.muted,fontSize:9.5,marginTop:3},progressNumber:{color:C.violet,fontWeight:'900',fontSize:16},track:{height:7,borderRadius:4,backgroundColor:'#1a2638',overflow:'hidden',marginTop:12},fill:{height:'100%',borderRadius:4,backgroundColor:C.violet},verifyFill:{height:'100%',borderRadius:4,backgroundColor:C.green},next:{color:C.cyan2,fontSize:9.5,fontWeight:'700',marginTop:8},complete:{color:C.green,fontSize:9.5,fontWeight:'800',marginTop:8},checkRow:{flexDirection:'row',gap:18,marginTop:9},check:{flexDirection:'row',alignItems:'center',gap:5},checkText:{color:C.muted,fontSize:9.5,fontWeight:'700'},section:{color:C.faint,fontSize:9,fontWeight:'900',letterSpacing:1.8,marginTop:22,marginBottom:5},menu:{minHeight:65,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderBottomColor:'#202b3a'},menuIcon:{width:40,height:40,borderRadius:14,backgroundColor:C.panel2,alignItems:'center',justifyContent:'center'},menuTitle:{color:C.text,fontWeight:'800',fontSize:13},menuSub:{color:C.muted,fontSize:10,marginTop:3},logout:{height:50,borderRadius:16,borderWidth:1,borderColor:'rgba(255,66,89,.38)',backgroundColor:'rgba(255,66,89,.08)',alignItems:'center',justifyContent:'center',marginTop:24,flexDirection:'row',gap:8},logoutText:{color:'#ff8ea0',fontWeight:'900'}});
