import React,{useEffect,useState} from 'react';
import {Alert,Modal,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {del,patch,post} from '../../api/client';
import {C} from '../../theme';
import NativeIcon from '../../components/NativeIcon';
import ProtectedImage from '../../components/ProtectedImage';
import {Action,Card,Choice,Field,MultiChoice,Toggle,commonStyles as cs} from '../account/AccountSettingFields';
export type Mask={id:number;mask_type:string;geometry:{x:number;y:number;width:number;height:number};intensity:number;enabled:boolean};
export type Photo={id:number;url?:string;caption?:string|null;visibility:string;reveal_after_connection:boolean;masks:Mask[];selected_members:any[]};
export default function DiscreetPhotoPrivacy({photos,audiences,connections,reload,setError}:{photos:Photo[];audiences:any;connections:any;reload:()=>void;setError:(x:string)=>void}){return <>{photos.length?photos.map(p=><PhotoCard key={p.id} photo={p} audiences={audiences} connections={connections} reload={reload} setError={setError}/>):<Text style={s.empty}>No editable profile photos yet.</Text>}</>}
function PhotoCard({photo,audiences,connections,reload,setError}:{photo:Photo;audiences:any;connections:any;reload:()=>void;setError:(x:string)=>void}){const [visibility,setVisibility]=useState(photo.visibility),[reveal,setReveal]=useState(photo.reveal_after_connection),[selected,setSelected]=useState<any[]>(photo.selected_members.map(x=>Number(x.id))),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);useEffect(()=>{setVisibility(photo.visibility);setReveal(photo.reveal_after_connection);setSelected(photo.selected_members.map(x=>Number(x.id)))},[photo]);const save=async()=>{setBusy(true);try{await patch(`/me/discreet/photos/${photo.id}`,{visibility,reveal_after_connection:reveal,selected_user_ids:selected});await reload()}catch(e:any){setError(String(e?.message||e))}finally{setBusy(false)}};const remove=(m:Mask)=>Alert.alert('Remove privacy mask?',`Remove this ${m.mask_type.replace(/_/g,' ')} region?`,[{text:'Cancel',style:'cancel'},{text:'Remove',style:'destructive',onPress:async()=>{try{await del(`/me/discreet/photos/${photo.id}/masks/${m.id}`);await reload()}catch(e:any){setError(String(e?.message||e))}}}]);return <Card title={photo.caption||`Photo #${photo.id}`} copy="Tap a mask overlay to remove it. Owners preview the original plus overlays; other viewers are protected server-side."><View style={s.photoWrap}><ProtectedImage uri={photo.url} fallback="PG" style={s.photo}/>{photo.masks.filter(m=>m.enabled).map(m=><Pressable key={m.id} onPress={()=>remove(m)} style={[s.mask,{left:`${m.geometry.x*100}%` as any,top:`${m.geometry.y*100}%` as any,width:`${m.geometry.width*100}%` as any,height:`${m.geometry.height*100}%` as any}]}><Text style={s.maskText}>{m.mask_type.replace(/_/g,' ')}</Text></Pressable>)}</View><Choice label="Audience" value={visibility} options={audiences} onChange={setVisibility}/>{visibility==='selected'?<MultiChoice label="Selected connections" values={selected} options={connections} onChange={v=>setSelected(v.map(Number))}/>:null}<Toggle label="Reveal only after accepted connection" value={reveal} onChange={setReveal}/><View style={cs.buttonRow}><Action label={busy?'Saving…':'Save privacy'} onPress={save} disabled={busy}/><Action label="Add mask region" onPress={()=>setOpen(true)}/></View><MaskModal open={open} photoId={photo.id} close={()=>setOpen(false)} done={async()=>{setOpen(false);await reload()}} setError={setError}/></Card>}
function MaskModal({open,photoId,close,done,setError}:{open:boolean;photoId:number;close:()=>void;done:()=>void;setError:(x:string)=>void}){const [type,setType]=useState('manual_blur'),[x,setX]=useState('20'),[y,setY]=useState('20'),[w,setW]=useState('35'),[h,setH]=useState('25'),[intensity,setIntensity]=useState('70');const save=async()=>{try{const n=(v:string)=>Math.max(0,Math.min(100,Number(v)||0))/100;await post(`/me/discreet/photos/${photoId}/masks`,{mask_type:type,geometry:{x:n(x),y:n(y),width:n(w),height:n(h)},intensity:Number(intensity)||70,enabled:true});done()}catch(e:any){setError(String(e?.message||e))}};return <Modal visible={open} transparent animationType="slide" onRequestClose={close}><Pressable style={s.shade} onPress={close}><Pressable style={s.sheet} onPress={()=>{}}><View style={s.head}><Text style={s.title}>Add privacy mask</Text><Pressable onPress={close}><NativeIcon ios="xmark.circle.fill" android="cancel" size={24} color={C.faint}/></Pressable></View><Choice label="Mask type" value={type} options={{face:'Face',eyes:'Eyes',tattoo:'Tattoo',manual_blur:'Manual blur'}} onChange={setType}/><Text style={s.help}>Enter the mask box as percentages of the photo. At most 32 regions can be stored per photo.</Text><View style={s.grid}><Mini label="Left %" value={x} set={setX}/><Mini label="Top %" value={y} set={setY}/><Mini label="Width %" value={w} set={setW}/><Mini label="Height %" value={h} set={setH}/></View><Field label="Intensity (10–100)" value={intensity} onChange={setIntensity} keyboard="numeric"/><Pressable onPress={save} style={s.save}><Text style={s.saveText}>Add mask</Text></Pressable></Pressable></Pressable></Modal>}
function Mini({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <View style={s.mini}><Text style={s.miniLabel}>{label}</Text><TextInput value={value} onChangeText={set} keyboardType="numeric" style={s.input}/></View>}
const s=StyleSheet.create({empty:{color:C.faint,fontSize:10,paddingVertical:10},photoWrap:{width:'100%',aspectRatio:1.15,borderRadius:16,overflow:'hidden',backgroundColor:C.bg2,position:'relative'},photo:{width:'100%',height:'100%'},mask:{position:'absolute',backgroundColor:'rgba(7,14,24,.76)',borderWidth:1.5,borderColor:C.cyan2,alignItems:'center',justifyContent:'center',minWidth:22,minHeight:18},maskText:{color:'#fff',fontSize:7,fontWeight:'900',textTransform:'uppercase'},shade:{flex:1,backgroundColor:'rgba(0,0,0,.7)',justifyContent:'flex-end'},sheet:{maxHeight:'88%',backgroundColor:C.panel,borderTopLeftRadius:24,borderTopRightRadius:24,borderWidth:1,borderColor:C.line,padding:16},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{color:C.text,fontSize:16,fontWeight:'900'},help:{color:C.muted,fontSize:9.5,lineHeight:14,marginTop:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:10},mini:{width:'48%'},miniLabel:{color:C.muted,fontSize:9,fontWeight:'800',marginBottom:4},input:{height:42,borderRadius:12,borderWidth:1,borderColor:C.line,backgroundColor:C.bg2,color:C.text,paddingHorizontal:10},save:{height:48,borderRadius:15,backgroundColor:C.violet,alignItems:'center',justifyContent:'center',marginTop:14},saveText:{color:'#fff',fontWeight:'900'}});
