import React,{useEffect,useRef,useState} from 'react';
import {AppState,Pressable,StatusBar,StyleSheet,Text,TextInput,View} from 'react-native';
import {appLockStatus,AppLockStatus,unlockWithBiometric,verifyAppLockPin} from '../security/AppLock';
import {C} from '../theme';
import NativeIcon from './NativeIcon';
import BrandLogo from './BrandLogo';

export default function AppLockGate({children}:{children:React.ReactNode}){
  const [status,setStatus]=useState<AppLockStatus|null>(null);const [locked,setLocked]=useState(false);const [privacyHidden,setPrivacyHidden]=useState(true);const [pin,setPin]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const backgroundAt=useRef(0);const autoPrompted=useRef(false);
  useEffect(()=>{let live=true;appLockStatus().then(s=>{if(!live)return;setStatus(s);setLocked(s.enabled);setPrivacyHidden(false)}).catch(()=>{if(live){setStatus({enabled:false,biometric:false,timeoutSeconds:15,biometryType:null,hasPin:false});setPrivacyHidden(false)}});const sub=AppState.addEventListener('change',async state=>{if(state==='inactive'||state==='background'){backgroundAt.current=Date.now();setPrivacyHidden(true);return}if(state==='active'){const current=await appLockStatus().catch(()=>null);if(!live||!current)return;setStatus(current);const away=backgroundAt.current?Math.max(0,(Date.now()-backgroundAt.current)/1000):0;backgroundAt.current=0;if(current.enabled&&away>=current.timeoutSeconds){autoPrompted.current=false;setLocked(true)}else setLocked(false);setPrivacyHidden(false)}});return()=>{live=false;sub.remove()}},[]);
  useEffect(()=>{if(!locked||!status?.enabled||!status.biometric||autoPrompted.current)return;autoPrompted.current=true;setTimeout(()=>biometricUnlock(),220)},[locked,status?.enabled,status?.biometric]);
  const biometricUnlock=async()=>{if(busy)return;setBusy(true);setError('');const ok=await unlockWithBiometric();setBusy(false);if(ok){setPin('');setLocked(false);autoPrompted.current=false}else setError('Biometric unlock was not completed. Use your Private Gather PIN or try again.')};
  const pinUnlock=async()=>{if(busy||pin.length<4)return;setBusy(true);setError('');const ok=await verifyAppLockPin(pin);setBusy(false);if(ok){setPin('');setLocked(false);autoPrompted.current=false}else{setPin('');setError('Incorrect Private Gather PIN.')}};
  if(!status||privacyHidden)return <View style={s.privacy}><StatusBar hidden/><BrandLogo compact/></View>;
  if(!locked||!status.enabled)return <>{children}</>;
  return <View style={s.page}><StatusBar barStyle="light-content" backgroundColor={C.bg}/><View style={s.card}><BrandLogo/><View style={s.lock}><NativeIcon ios="lock.fill" android="lock" size={32} color={C.violet}/></View><Text style={s.title}>Private Gather is locked</Text><Text style={s.copy}>Unlock with {biometryLabel(status.biometryType)} or your Private Gather PIN.</Text>{status.biometric?<Pressable disabled={busy} onPress={biometricUnlock} style={s.biometric}><NativeIcon ios="faceid" android="fingerprint" size={24} color="#fff"/><Text style={s.biometricText}>{busy?'Checking…':`Use ${biometryLabel(status.biometryType)}`}</Text></Pressable>:null}<View style={s.pinRow}><TextInput value={pin} onChangeText={v=>setPin(v.replace(/\D/g,'').slice(0,8))} keyboardType="number-pad" secureTextEntry maxLength={8} placeholder="Private Gather PIN" placeholderTextColor={C.faint} style={s.input} onSubmitEditing={pinUnlock}/><Pressable disabled={busy||pin.length<4} onPress={pinUnlock} style={[s.go,(busy||pin.length<4)&&s.disabled]}><NativeIcon ios="arrow.right" android="arrow_forward" size={21} color="#fff"/></Pressable></View>{error?<Text style={s.error}>{error}</Text>:null}<Text style={s.note}>Your PIN and app-lock credentials stay in this device’s secure Keychain/Keystore.</Text></View></View>;
}
function biometryLabel(type:string|null){const value=String(type||'').toLowerCase();if(value.includes('face'))return'Face ID';if(value.includes('touch'))return'Touch ID';if(value.includes('finger'))return'Fingerprint';if(value.includes('iris'))return'Iris';return'biometrics'}
const s=StyleSheet.create({privacy:{flex:1,backgroundColor:C.bg,alignItems:'center',justifyContent:'center'},page:{flex:1,backgroundColor:C.bg,alignItems:'center',justifyContent:'center',padding:24},card:{width:'100%',maxWidth:430,borderRadius:28,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,padding:24,alignItems:'center'},lock:{width:70,height:70,borderRadius:24,backgroundColor:'rgba(155,92,255,.12)',borderWidth:1,borderColor:'rgba(155,92,255,.35)',alignItems:'center',justifyContent:'center',marginTop:22},title:{color:C.text,fontSize:22,fontWeight:'900',marginTop:16},copy:{color:C.muted,fontSize:11,lineHeight:17,textAlign:'center',marginTop:7,maxWidth:310},biometric:{height:50,borderRadius:17,backgroundColor:C.violet,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,alignSelf:'stretch',marginTop:22},biometricText:{color:'#fff',fontWeight:'900'},pinRow:{flexDirection:'row',alignSelf:'stretch',gap:8,marginTop:10},input:{flex:1,height:50,borderRadius:17,borderWidth:1,borderColor:C.line,backgroundColor:C.panel2,color:C.text,paddingHorizontal:15,fontSize:14,letterSpacing:1},go:{width:50,height:50,borderRadius:17,backgroundColor:C.pink,alignItems:'center',justifyContent:'center'},disabled:{opacity:.35},error:{color:'#ff9ba9',fontSize:10,lineHeight:15,textAlign:'center',marginTop:11},note:{color:C.faint,fontSize:8.5,lineHeight:13,textAlign:'center',marginTop:18,maxWidth:300}});
