import React,{useMemo,useState} from 'react';
import {Modal,Pressable,ScrollView,StyleSheet,Switch,Text,TextInput,View} from 'react-native';
import {C} from '../../theme';
import NativeIcon from '../../components/NativeIcon';

export function Card({title,copy,children}:{title:string;copy?:string;children:React.ReactNode}){return <View style={s.card}><Text style={s.cardTitle}>{title}</Text>{copy?<Text style={s.cardCopy}>{copy}</Text>:null}<View style={{marginTop:8}}>{children}</View></View>}
export function Field({label,value,onChange,multiline=false,maxLength,keyboard='default',placeholder}:{label:string;value:any;onChange:(v:string)=>void;multiline?:boolean;maxLength?:number;keyboard?:any;placeholder?:string}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value===null||value===undefined?'':String(value)} onChangeText={onChange} multiline={multiline} maxLength={maxLength} keyboardType={keyboard} placeholder={placeholder} placeholderTextColor={C.faint} style={[s.input,multiline&&s.multi]}/></View>}
export function Toggle({label,sub,value,onChange,disabled=false}:{label:string;sub?:string;value:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){return <View style={[s.toggle,disabled&&{opacity:.5}]}><View style={{flex:1}}><Text style={s.toggleTitle}>{label}</Text>{sub?<Text style={s.toggleSub}>{sub}</Text>:null}</View><Switch disabled={disabled} value={value} onValueChange={onChange} trackColor={{false:'#263650',true:C.violet}} thumbColor={value?C.cyan2:'#d9e2f0'}/></View>}
export function Action({label,onPress,disabled}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,disabled&&{opacity:.5}]}><Text style={s.actionText}>{label}</Text></Pressable>}
export function Menu({icon,title,sub,onPress}:{icon:[string,string];title:string;sub:string;onPress:()=>void}){return <Pressable onPress={onPress} style={s.menu}><View style={s.menuIcon}><NativeIcon ios={icon[0]} android={icon[1]} size={20} color={C.cyan2}/></View><View style={{flex:1}}><Text style={s.menuTitle}>{title}</Text><Text style={s.menuSub}>{sub}</Text></View><NativeIcon ios="chevron.right" android="chevron_right" size={20} color={C.faint}/></Pressable>}
export function Empty({text}:{text:string}){return <Text style={s.empty}>{text}</Text>}
export function SecurityRow({title,sub,action,onPress,disabled=false}:{title:string;sub:string;action:string;onPress:()=>void;disabled?:boolean}){return <View style={s.securityRow}><View style={{flex:1}}><Text style={s.securityTitle}>{title}</Text><Text style={s.securitySub}>{sub}</Text></View><Pressable disabled={disabled} onPress={onPress} style={[s.smallAction,disabled&&{opacity:.45}]}><Text style={s.smallActionText}>{action}</Text></Pressable></View>}
export function Choice({label,value,options,onChange}:{label:string;value:any;options:any;onChange:(v:any)=>void}){const [open,setOpen]=useState(false);const rows=useMemo(()=>normalizeOptions(options),[options]);const chosen=rows.find(r=>String(r.value)===String(value));return <View style={s.field}><Text style={s.label}>{label}</Text><Pressable onPress={()=>setOpen(true)} style={s.select}><Text style={[s.selectText,!chosen&&{color:C.faint}]}>{chosen?.label||'Not specified'}</Text><NativeIcon ios="chevron.up.chevron.down" android="unfold_more" size={17} color={C.faint}/></Pressable><OptionModal open={open} setOpen={setOpen} title={label} rows={rows} value={value} onChange={onChange}/></View>}
export function MultiChoice({label,values,options,onChange}:{label:string;values:any[];options:any;onChange:(v:any[])=>void}){const [open,setOpen]=useState(false);const rows=useMemo(()=>normalizeOptions(options),[options]);const selected=new Set((values||[]).map(String));return <View style={s.field}><Text style={s.label}>{label}</Text><Pressable onPress={()=>setOpen(true)} style={s.select}><Text style={s.selectText}>{values?.length?`${values.length} selected`:'None selected'}</Text><NativeIcon ios="chevron.up.chevron.down" android="unfold_more" size={17} color={C.faint}/></Pressable><Modal visible={open} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><Pressable style={s.modalShade} onPress={()=>setOpen(false)}><Pressable style={s.modalCard} onPress={()=>{}}><ModalHead title={label} close={()=>setOpen(false)}/><ScrollView>{rows.map(r=>{const yes=selected.has(String(r.value));return <Pressable key={String(r.value)} onPress={()=>onChange(yes?(values||[]).filter(v=>String(v)!==String(r.value)):[...(values||[]),r.value])} style={s.option}><Check yes={yes}/><Text style={s.optionText}>{r.label}</Text></Pressable>})}</ScrollView><Pressable onPress={()=>setOpen(false)} style={s.done}><Text style={s.doneText}>Done</Text></Pressable></Pressable></Pressable></Modal></View>}
function OptionModal({open,setOpen,title,rows,value,onChange}:{open:boolean;setOpen:(v:boolean)=>void;title:string;rows:any[];value:any;onChange:(v:any)=>void}){return <Modal visible={open} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><Pressable style={s.modalShade} onPress={()=>setOpen(false)}><Pressable style={s.modalCard} onPress={()=>{}}><ModalHead title={title} close={()=>setOpen(false)}/><ScrollView><Pressable onPress={()=>{onChange(null);setOpen(false)}} style={s.option}><Check yes={value===null||value===''}/><Text style={s.optionText}>Not specified</Text></Pressable>{rows.map(r=>{const yes=String(r.value)===String(value);return <Pressable key={String(r.value)} onPress={()=>{onChange(r.value);setOpen(false)}} style={s.option}><Check yes={yes}/><Text style={s.optionText}>{r.label}</Text></Pressable>})}</ScrollView></Pressable></Pressable></Modal>}
function ModalHead({title,close}:{title:string;close:()=>void}){return <View style={s.modalHead}><Text style={s.modalTitle}>{title}</Text><Pressable onPress={close}><NativeIcon ios="xmark.circle.fill" android="cancel" size={24} color={C.faint}/></Pressable></View>}
function Check({yes}:{yes:boolean}){return <NativeIcon ios={yes?'checkmark.circle.fill':'circle'} android={yes?'check_circle':'radio_button_unchecked'} size={20} color={yes?C.green:C.faint}/>}
function normalizeOptions(options:any){if(Array.isArray(options))return options.map(v=>({value:v,label:typeof v==='number'?String(v):String(v).replace(/_/g,' ')}));if(options&&typeof options==='object')return Object.entries(options).map(([value,label])=>({value,label:String(label)}));return []}

export const commonStyles=StyleSheet.create({section:{color:C.faint,fontSize:9,fontWeight:'900',letterSpacing:1.8,marginTop:22,marginBottom:5},note:{borderRadius:16,borderWidth:1,borderColor:C.line,backgroundColor:C.panel2,padding:12,flexDirection:'row',gap:9,alignItems:'flex-start',marginTop:12},noteText:{flex:1,color:C.muted,fontSize:9.5,lineHeight:14},buttonRow:{flexDirection:'row',gap:9,marginTop:9}});
const s=StyleSheet.create({card:{borderRadius:20,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,padding:14,marginTop:12},cardTitle:{color:C.text,fontSize:14,fontWeight:'900'},cardCopy:{color:C.muted,fontSize:10,lineHeight:15,marginTop:4},field:{marginTop:12},label:{color:C.muted,fontSize:9.5,fontWeight:'800',marginBottom:5},input:{minHeight:44,borderRadius:13,borderWidth:1,borderColor:C.line,backgroundColor:C.bg2,color:C.text,paddingHorizontal:12,paddingVertical:10,fontSize:12},multi:{minHeight:96,textAlignVertical:'top'},toggle:{minHeight:54,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:'#1d2939'},toggleTitle:{color:C.text,fontSize:11.5,fontWeight:'800'},toggleSub:{color:C.muted,fontSize:9.5,marginTop:2},select:{height:45,borderRadius:13,borderWidth:1,borderColor:C.line,backgroundColor:C.bg2,paddingHorizontal:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},selectText:{color:C.text,fontSize:11.5,fontWeight:'700',textTransform:'capitalize'},action:{minHeight:38,borderRadius:12,borderWidth:1,borderColor:C.line,backgroundColor:C.panel2,paddingHorizontal:12,alignItems:'center',justifyContent:'center',flex:1},actionText:{color:C.cyan2,fontWeight:'900',fontSize:10},menu:{minHeight:66,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderBottomColor:'#202b3a'},menuIcon:{width:40,height:40,borderRadius:14,backgroundColor:C.panel2,alignItems:'center',justifyContent:'center'},menuTitle:{color:C.text,fontWeight:'800',fontSize:13},menuSub:{color:C.muted,fontSize:10,marginTop:3},empty:{color:C.faint,fontSize:10,paddingVertical:10},securityRow:{minHeight:58,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderBottomColor:'#1d2939'},securityTitle:{color:C.text,fontWeight:'800',fontSize:11.5},securitySub:{color:C.muted,fontSize:9.5,marginTop:3},smallAction:{borderWidth:1,borderColor:C.line,borderRadius:11,paddingHorizontal:10,paddingVertical:8},smallActionText:{color:C.cyan2,fontWeight:'900',fontSize:9.5},modalShade:{flex:1,backgroundColor:'rgba(0,0,0,.68)',justifyContent:'flex-end'},modalCard:{maxHeight:'76%',backgroundColor:C.panel,borderTopLeftRadius:24,borderTopRightRadius:24,borderWidth:1,borderColor:C.line,padding:15},modalHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingBottom:8},modalTitle:{color:C.text,fontSize:15,fontWeight:'900'},option:{minHeight:48,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderBottomColor:'#1d2939'},optionText:{color:C.text,fontSize:11.5,fontWeight:'700',textTransform:'capitalize'},done:{height:46,borderRadius:14,backgroundColor:C.violet,alignItems:'center',justifyContent:'center',marginTop:10},doneText:{color:'#fff',fontWeight:'900'}});
