import React from 'react';
import {Alert,View} from 'react-native';
import {del} from '../../api/client';
import {Card,Empty,SecurityRow} from './AccountSettingFields';
export function SafetyForm({data,reload,setError}:{data:any;reload:()=>void;setError:(x:string)=>void}){const act=async(path:string)=>{try{await del(path);reload()}catch(e:any){setError(String(e?.message||e))}};return <View><Card title="Blocked members" copy="Blocking also removes favorites/connections and revokes shared location access.">{(data.blocked||[]).length?(data.blocked||[]).map((m:any)=><SafetyRow key={`b${m.id}`} member={m} label="Unblock" onPress={()=>act(`/members/${m.id}/block`)}/>):<Empty text="No blocked members."/>}</Card><Card title="Hidden members" copy="Hidden members stay out of your discovery experience.">{(data.hidden||[]).length?(data.hidden||[]).map((m:any)=><SafetyRow key={`h${m.id}`} member={m} label="Unhide" onPress={()=>act(`/members/${m.id}/hide`)}/>):<Empty text="No hidden members."/>}</Card></View>}
function SafetyRow({member,label,onPress}:{member:any;label:string;onPress:()=>void}){return <SecurityRow title={member.display_name||member.username} sub={`@${member.username}`} action={label} onPress={onPress}/>}
export function SecurityForm({data,reload,setError}:{data:any;reload:()=>void;setError:(x:string)=>void}){const revoke=(path:string,label:string)=>Alert.alert('Revoke access',`Revoke ${label}?`,[{text:'Cancel',style:'cancel'},{text:'Revoke',style:'destructive',onPress:async()=>{try{await del(path);reload()}catch(e:any){setError(String(e?.message||e))}}}]);return <View><Card title="Native devices">{(data.native_devices||[]).length?(data.native_devices||[]).map((d:any)=><SecurityRow key={`d${d.id}`} title={d.device_name||`${d.platform} device`} sub={`${d.platform} · app ${d.app_version||'unknown'} · seen ${formatDate(d.last_seen_at)}`} action="Remove" onPress={()=>revoke(`/me/security/devices/${d.id}`,d.device_name||'this device')}/>):<Empty text="No registered native devices."/>}</Card><Card title="Native sign-ins">{(data.native_tokens||[]).length?(data.native_tokens||[]).map((t:any)=><SecurityRow key={`t${t.id}`} title={t.name||'Native client'} sub={`${t.current?'Current · ':''}expires ${formatDate(t.expires_at)}`} action={t.current?'Current':'Revoke'} disabled={t.current} onPress={()=>revoke(`/me/security/tokens/${t.id}`,t.name||'this native sign-in')}/>):<Empty text="No native API tokens."/>}</Card><Card title="Website sessions">{(data.web_sessions||[]).length?(data.web_sessions||[]).map((w:any)=><SecurityRow key={`w${w.id}`} title={shortAgent(w.user_agent)} sub={`Last active ${formatDate(w.last_active_at)}`} action="Revoke" onPress={()=>revoke(`/me/security/sessions/${encodeURIComponent(w.id)}`,'this website session')}/>):<Empty text="No active website sessions."/>}</Card></View>}
function formatDate(value:any){if(!value)return 'unknown';try{return new Date(value).toLocaleString()}catch{return String(value)}}
function shortAgent(value:any){const x=String(value||'Website session');return x.length>55?x.slice(0,52)+'…':x}
