import React from 'react';
import {Text,View} from 'react-native';
import {C} from '../../theme';
import NativeIcon from '../../components/NativeIcon';
import {Card,Choice,Field,MultiChoice,Toggle,commonStyles as cs} from './AccountSettingFields';

export default function AccountProfileForm({data,draft,set}:{data:any;draft:any;set:(k:string,v:any)=>void}){const o=data.options||{};const multi=!!data.read_only?.multi_person;return <View>
 <Card title="Public profile" copy="These fields use the same validation and privacy rules as the website editor."><Field label="Display name" value={draft.display_name} onChange={v=>set('display_name',v)} maxLength={80}/><Field label="Headline" value={draft.headline} onChange={v=>set('headline',v)} maxLength={120}/><Field label="City" value={draft.city} onChange={v=>set('city',v)} maxLength={80}/><Choice label="State" value={draft.state} options={o.states} onChange={v=>set('state',v)}/><Choice label="Lifestyle experience" value={draft.lifestyle_experience} options={o.lifestyle_experience} onChange={v=>set('lifestyle_experience',v)}/><Choice label="Relationship status" value={draft.relationship_status} options={o.relationship_status} onChange={v=>set('relationship_status',v)}/><Choice label="Social style" value={draft.social_style} options={o.social_style} onChange={v=>set('social_style',v)}/><Choice label="Meet preference" value={draft.meet_preference} options={o.meet_preference} onChange={v=>set('meet_preference',v)}/><Choice label="Hosting preference" value={draft.hosting_preference} options={o.hosting_preference} onChange={v=>set('hosting_preference',v)}/><Choice label="Travel preference" value={draft.travel_preference} options={o.travel_preference} onChange={v=>set('travel_preference',v)}/></Card>
 <Card title="About & boundaries"><Field label="About me" value={draft.bio} onChange={v=>set('bio',v)} multiline maxLength={2000}/><Field label="What I'm looking for" value={draft.looking_for} onChange={v=>set('looking_for',v)} multiline maxLength={1600}/><Field label="Boundaries & expectations" value={draft.boundaries} onChange={v=>set('boundaries',v)} multiline maxLength={1600}/>{multi?<Field label="Group / profile member details" value={draft.group_member_details} onChange={v=>set('group_member_details',v)} multiline maxLength={1600}/>:null}</Card>
 <Card title="Interests & discovery"><MultiChoice label="Lifestyle interests" values={draft.lifestyle_interests||[]} options={o.lifestyle_interests} onChange={v=>set('lifestyle_interests',v)}/><MultiChoice label="Interests / kinks" values={draft.profile_kinks||[]} options={o.kinks} onChange={v=>set('profile_kinks',v)}/><MultiChoice label="Seeking profile types" values={draft.seeking_profile_types||[]} options={o.seeking_profile_types} onChange={v=>set('seeking_profile_types',v)}/><MultiChoice label="Seeking connection types" values={draft.seeking_connection_types||[]} options={o.seeking_connection_types} onChange={v=>set('seeking_connection_types',v)}/><Field label="Minimum age" value={draft.seeking_age_min} onChange={v=>set('seeking_age_min',v===''?null:Number(v))} keyboard="numeric"/><Field label="Maximum age" value={draft.seeking_age_max} onChange={v=>set('seeking_age_max',v===''?null:Number(v))} keyboard="numeric"/><Choice label="Search distance" value={draft.seeking_distance_miles} options={o.seeking_distance_miles} onChange={v=>set('seeking_distance_miles',v)}/><Toggle label="Verified members only" value={!!draft.seeking_verified_only} onChange={v=>set('seeking_verified_only',v)}/><Toggle label="Show compatibility score" value={!!draft.show_compatibility_score} onChange={v=>set('show_compatibility_score',v)}/></Card>
 <Person title="Primary person" prefix="primary" draft={draft} set={set} options={o}/>{multi?<Person title="Second person" prefix="secondary" draft={draft} set={set} options={o}/>:null}
 {'date_of_birth' in draft?<Card title="Age verification"><Field label="Birthdate (YYYY-MM-DD)" value={draft.date_of_birth} onChange={v=>set('date_of_birth',v)} placeholder="YYYY-MM-DD"/></Card>:null}{'secondary_date_of_birth' in draft?<Card title="Second person age"><Field label="Birthdate (YYYY-MM-DD)" value={draft.secondary_date_of_birth} onChange={v=>set('secondary_date_of_birth',v)} placeholder="YYYY-MM-DD"/></Card>:null}
 <View style={cs.note}><NativeIcon ios="photo.on.rectangle.angled" android="photo_library" size={18} color={C.cyan2}/><Text style={cs.noteText}>Avatar and cover upload endpoints are live in 1.1.202. Camera/gallery editing stays in the dedicated native media pipeline slice.</Text></View>
 </View>}
function Person({title,prefix,draft,set,options}:{title:string;prefix:'primary'|'secondary';draft:any;set:(k:string,v:any)=>void;options:any}){const k=(x:string)=>`${prefix}_${x}`;return <Card title={title}><Field label="Name" value={draft[k('person_name')]} onChange={v=>set(k('person_name'),v)} maxLength={80}/><Choice label="Sexual orientation" value={draft[k('sexual_orientation')]} options={options.sexual_orientation} onChange={v=>set(k('sexual_orientation'),v)}/><Choice label="Ethnicity" value={draft[k('ethnicity')]} options={options.ethnicity} onChange={v=>set(k('ethnicity'),v)}/><Choice label="Hair" value={draft[k('hair_color')]} options={options.hair_color} onChange={v=>set(k('hair_color'),v)}/><Choice label="Eyes" value={draft[k('eye_color')]} options={options.eye_color} onChange={v=>set(k('eye_color'),v)}/><Choice label="Height" value={draft[k('height')]} options={options.height} onChange={v=>set(k('height'),v)}/><Choice label="Weight" value={draft[k('weight')]} options={options.weight} onChange={v=>set(k('weight'),v)}/><Choice label="Body type" value={draft[k('body_type')]} options={options.body_type} onChange={v=>set(k('body_type'),v)}/><Choice label="Drinking" value={draft[k('drinking_preference')]} options={options.drinking_preference} onChange={v=>set(k('drinking_preference'),v)}/><Choice label="Smoking" value={draft[k('smoking_preference')]} options={options.smoking_preference} onChange={v=>set(k('smoking_preference'),v)}/><Choice label="420" value={draft[k('420_preference')]} options={options.four_twenty_preference} onChange={v=>set(k('420_preference'),v)}/><Choice label="Grooming" value={draft[k('grooming_style')]} options={options.grooming_style} onChange={v=>set(k('grooming_style'),v)}/><Choice label="Penis size (if applicable)" value={draft[k('penis_size')]} options={options.penis_size} onChange={v=>set(k('penis_size'),v)}/><Choice label="Chest size (if applicable)" value={draft[k('chest_size')]} options={options.chest_size} onChange={v=>set(k('chest_size'),v)}/></Card>}
