import React,{useState} from 'react';
import {ActivityIndicator,KeyboardAvoidingView,Platform,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {C} from '../../../theme';
import BrandLogo from '../../../components/BrandLogo';

export default function MessengerLoginScreen({onLogin}:{onLogin:(email:string,password:string)=>Promise<void>}){
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const submit=async()=>{if(!email.trim()||!password||busy)return;setBusy(true);setError('');try{await onLogin(email.trim(),password)}catch(e:any){setError(String(e?.message||e))}finally{setBusy(false)}};
  return <SafeAreaView style={s.page}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.wrap}><BrandLogo compact/><Text style={s.title}>Private Gather Messenger</Text><Text style={s.sub}>Fast, private messaging and calling for Private Gather.</Text>{error?<Text style={s.error}>{error}</Text>:null}<TextInput autoCapitalize="none" autoCorrect={false} keyboardType="email-address" value={email} onChangeText={setEmail} placeholder="Email" placeholderTextColor={C.faint} style={s.input}/><TextInput secureTextEntry value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor={C.faint} style={s.input} onSubmitEditing={submit}/><Pressable onPress={submit} disabled={busy||!email.trim()||!password} style={[s.button,(busy||!email.trim()||!password)&&s.disabled]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>Sign in to Messenger</Text>}</Pressable><Text style={s.note}>If you open Messenger from the Private Gather app, it can sign you in automatically with a one-time handoff.</Text></View></KeyboardAvoidingView></SafeAreaView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},flex:{flex:1},wrap:{flex:1,justifyContent:'center',paddingHorizontal:24,gap:12},title:{color:C.text,fontSize:27,fontWeight:'900',marginTop:10},sub:{color:C.muted,fontSize:13,lineHeight:19,marginBottom:8},error:{color:'#ff8d8d',fontSize:12},input:{height:52,borderRadius:16,backgroundColor:C.panel2,borderWidth:1,borderColor:C.line,color:C.text,paddingHorizontal:15,fontSize:15},button:{height:52,borderRadius:17,backgroundColor:C.pink,alignItems:'center',justifyContent:'center',marginTop:3},disabled:{opacity:.45},buttonText:{color:'#fff',fontWeight:'900',fontSize:14},note:{color:C.faint,fontSize:10,lineHeight:15,textAlign:'center',marginTop:10}});
