import React from 'react';
import {Alert,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {C} from '../../../theme';
import NativeIcon from '../../../components/NativeIcon';
import BrandLogo from '../../../components/BrandLogo';

export default function MessengerSettingsScreen({onBack,onSafety,onLogout}:{onBack:()=>void;onSafety:()=>void;onLogout:()=>void}){
  const signOut=()=>Alert.alert('Sign out of Messenger?','This signs this device out of Private Gather Messenger. Your Main app session is separate.',[{text:'Cancel',style:'cancel'},{text:'Sign out',style:'destructive',onPress:onLogout}]);
  return <SafeAreaView style={s.page} edges={['top','left','right']}><ScrollView contentContainerStyle={s.content}><View style={s.top}><Pressable onPress={onBack} style={s.back}><NativeIcon ios="chevron.left" android="arrow_back" size={22} color={C.cyan2}/><Text style={s.backText}>Back</Text></Pressable><Text style={s.title}>Messenger Settings</Text><View style={{width:68}}/></View><View style={s.brand}><BrandLogo/><Text style={s.brandTitle}>Private Gather Messenger</Text><Text style={s.brandCopy}>Calling, privacy and Messenger-specific device controls.</Text></View><Text style={s.section}>PRIVACY & SECURITY</Text><Pressable onPress={onSafety} style={s.row}><View style={s.icon}><NativeIcon ios="lock.shield.fill" android="shield_lock" size={22} color={C.violet}/></View><View style={{flex:1}}><Text style={s.rowTitle}>Safety Center & App Lock</Text><Text style={s.rowCopy}>Set Messenger’s own biometric/PIN lock for this device.</Text></View><NativeIcon ios="chevron.right" android="chevron_right" size={19} color={C.faint}/></Pressable><View style={s.note}><NativeIcon ios="info.circle.fill" android="info" size={17} color={C.cyan2}/><Text style={s.noteText}>Main and Messenger are separate native apps, so each maintains its own secure App Lock credentials and timeout.</Text></View><Text style={s.section}>ACCOUNT</Text><Pressable onPress={signOut} style={s.logout}><NativeIcon ios="rectangle.portrait.and.arrow.right" android="logout" size={19} color="#ff8ea0"/><Text style={s.logoutText}>Sign out of Messenger</Text></Pressable></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},content:{paddingHorizontal:16,paddingBottom:34},top:{height:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:68,flexDirection:'row',alignItems:'center',gap:3},backText:{color:C.cyan2,fontWeight:'800'},title:{color:C.text,fontSize:17,fontWeight:'900'},brand:{borderRadius:22,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,padding:18,alignItems:'center'},brandTitle:{color:C.text,fontSize:17,fontWeight:'900',marginTop:12},brandCopy:{color:C.muted,fontSize:10.5,lineHeight:16,textAlign:'center',marginTop:5},section:{color:C.faint,fontSize:9,fontWeight:'900',letterSpacing:1.7,marginTop:22,marginBottom:7},row:{minHeight:72,borderRadius:18,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,padding:12,flexDirection:'row',alignItems:'center',gap:11},icon:{width:44,height:44,borderRadius:15,backgroundColor:'rgba(155,92,255,.10)',alignItems:'center',justifyContent:'center'},rowTitle:{color:C.text,fontSize:12.5,fontWeight:'900'},rowCopy:{color:C.muted,fontSize:9.5,lineHeight:14,marginTop:3},note:{borderRadius:14,borderWidth:1,borderColor:'rgba(41,217,255,.20)',backgroundColor:'rgba(41,217,255,.05)',padding:10,flexDirection:'row',gap:8,marginTop:9},noteText:{flex:1,color:C.muted,fontSize:8.5,lineHeight:13},logout:{height:50,borderRadius:16,borderWidth:1,borderColor:'rgba(255,66,89,.38)',backgroundColor:'rgba(255,66,89,.08)',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},logoutText:{color:'#ff8ea0',fontWeight:'900'}});
