import React,{useCallback,useEffect,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,RefreshControl,StyleSheet,Text,View} from 'react-native';
import * as Notifications from 'expo-notifications';
import {SafeAreaView} from 'react-native-safe-area-context';
import {MessengerEngine} from '../MessengerEngine';
import {StoredConversation} from '../MessengerStore';
import {C} from '../../../theme';
import ProtectedImage from '../../../components/ProtectedImage';
import NativeIcon from '../../../components/NativeIcon';
import BrandLogo from '../../../components/BrandLogo';

export default function MessengerInboxScreen({engine,onConversation,onLogout}:{engine:MessengerEngine;onConversation:(id:number)=>void;onLogout:()=>void}){
  const [rows,setRows]=useState<StoredConversation[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');
  const fromCache=useCallback(async()=>{const cached=await engine.conversations();setRows(cached);setLoading(false);const unread=cached.reduce((sum,row)=>sum+Math.max(0,Number(row.unread||0)),0);Notifications.setBadgeCountAsync(unread).catch(()=>{})},[engine]);
  const refresh=useCallback(async()=>{try{setError('');await engine.refreshInbox()}catch(e:any){setError(String(e?.message||e))}finally{await fromCache()}},[engine,fromCache]);
  useEffect(()=>{let live=true;const load=()=>{if(live)fromCache().catch(()=>{})};const un=engine.subscribe('inbox',load);fromCache().then(()=>refresh()).catch(()=>refresh());return()=>{live=false;un()}},[engine,fromCache,refresh]);
  const pull=async()=>{setRefreshing(true);await refresh();setRefreshing(false)};
  return <SafeAreaView style={s.page} edges={['top','left','right']}><View style={s.header}><BrandLogo compact/><View style={s.headCopy}><Text style={s.title}>Messenger</Text><Text style={s.subtitle}>Private Gather</Text></View><Pressable accessibilityLabel="Messenger settings" onPress={onLogout} style={s.icon}><NativeIcon ios="gearshape.fill" android="settings" size={21} color={C.cyan2}/></Pressable></View>{error?<Text style={s.error}>{error}</Text>:null}{loading?<ActivityIndicator style={{marginTop:80}} color={C.pink}/>:<FlatList data={rows} keyExtractor={r=>String(r.id)} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={pull} tintColor={C.pink}/>} contentContainerStyle={rows.length?s.list:s.emptyList} renderItem={({item})=><Pressable onPress={()=>onConversation(item.id)} style={s.row}><View style={s.avatarWrap}><ProtectedImage uri={item.avatar_url} fallback={item.name} style={s.avatar}/>{item.presence?.online?<View style={s.online}/>:null}</View><View style={s.copy}><View style={s.nameLine}><Text numberOfLines={1} style={s.name}>{item.name||'Conversation'}</Text>{item.verified?<Text style={s.verified}>✓</Text>:null}</View><Text numberOfLines={1} style={[s.preview,Number(item.unread||0)>0&&s.previewUnread]}>{item.preview||'Private conversation'}</Text><Text numberOfLines={1} style={s.presence}>{item.presence?.label||item.updated_at||''}</Text></View>{Number(item.unread||0)>0?<View style={s.badge}><Text style={s.badgeText}>{Number(item.unread)>99?'99+':item.unread}</Text></View>:null}</Pressable>} ListEmptyComponent={<View style={s.empty}><NativeIcon ios="message.fill" android="chat_bubble" size={40} color={C.cyan2}/><Text style={s.emptyTitle}>Your conversations will appear here</Text><Text style={s.emptyText}>Start a conversation from a member profile in Private Gather.</Text></View>} />}</SafeAreaView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},header:{height:68,flexDirection:'row',alignItems:'center',paddingHorizontal:14,borderBottomWidth:1,borderBottomColor:C.line,gap:10},headCopy:{flex:1},title:{color:C.text,fontSize:19,fontWeight:'900'},subtitle:{color:C.muted,fontSize:10,marginTop:1},icon:{width:42,height:42,borderRadius:21,backgroundColor:C.panel2,alignItems:'center',justifyContent:'center'},error:{color:'#ff8d8d',fontSize:10,paddingHorizontal:14,paddingTop:7},list:{paddingBottom:28},emptyList:{flexGrow:1},row:{minHeight:82,flexDirection:'row',alignItems:'center',paddingHorizontal:14,paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#182332',gap:12},avatarWrap:{position:'relative'},avatar:{width:58,height:58,borderRadius:21},online:{position:'absolute',right:-1,bottom:1,width:14,height:14,borderRadius:7,backgroundColor:C.green,borderWidth:2,borderColor:C.bg},copy:{flex:1,minWidth:0},nameLine:{flexDirection:'row',alignItems:'center',gap:5},name:{color:C.text,fontSize:15,fontWeight:'900',maxWidth:'90%'},verified:{color:C.green,fontWeight:'900'},preview:{color:C.muted,fontSize:11,marginTop:5},previewUnread:{color:C.text,fontWeight:'800'},presence:{color:C.faint,fontSize:9,marginTop:4},badge:{minWidth:26,height:26,paddingHorizontal:6,borderRadius:13,backgroundColor:C.pink,alignItems:'center',justifyContent:'center'},badgeText:{color:'#fff',fontWeight:'900',fontSize:10},empty:{flex:1,alignItems:'center',justifyContent:'center',paddingHorizontal:38},emptyTitle:{color:C.text,fontSize:17,fontWeight:'900',marginTop:14,textAlign:'center'},emptyText:{color:C.muted,fontSize:11,lineHeight:16,textAlign:'center',marginTop:6}});
